README.md
getting-started/docker.md

Documentation for https://github.com/dunglas/api-platform/pull/7

Init docker documentation

---

schema-generator/configuration.md

Fix broken bullet list in `schema-generator/configuration.md`

Fix broken bullet list

---

api-bundle/validation.md

Requires dunglas/DunglasApiBundle#254

Add info on using dynamic validation groups with API bundle

---

api-bundle/filters.md

https://github.com/dunglas/DunglasApiBundle/pull/289

Update doc for SearchFilter

---

api-bundle/filters.md

Dunglas/DunglasApiBundle#242
Dunglas/DunglasApiBundle#337

Add documentation for filter on nested properties

---

schema-generator/configuration.md
schema-generator/getting-started.md

Documentation for api-platform/schema-generator#46.

[Schema Generator] Add documentation for the format of the RDFa URI

---

api-bundle/filters.md

See https://github.com/dunglas/DunglasApiBundle/pull/384

Case sensitive search filter

---

api-bundle/filters.md

In the test I was doing to make the `BooleanFilter` work using api-platform v2 and my core, I decided to updated the documentation on filters.
Didn't know if I needed to base from master or V1.
This is what I've done in my entity to make the filter work.

Filters V2

---

schema-generator/configuration.md

https://github.com/api-platform/doc/issues/22

Add documentation for embeddable

---

api-bundle/getting-started.md

(WIP) Document v2

---

api-bundle/angular-integration.md
api-bundle/controllers.md
api-bundle/data-providers.md
api-bundle/filters.md
api-bundle/operations.md
api-bundle/performances.md
api-bundle/serialization-groups-and-relations.md
api-bundle/the-event-system.md
api-bundle/validation.md

- adds a note about EAGER doctrine configuration for automatically joining relations on sub-object serialization
- various updates/fixes/typos...

Eager collections

---

core/external-vocabularies.md
core/operations.md
getting-started/api.md

Looking at the docs, i've seen some Resource left

hotfix: update doc according to recent PR

---

core/configuration.md

Related to api-platform/core#577

Remove the metadata section from config

---

core/content-negotiation.md

- Take in account itemOperation normalization 
- Take in account collectionOperation normalization

hotfix: take in account normalization on operations

---

core/getting-started.md
core/nelmio-api-doc.md
index.md

Fix tutorial links

---

core/content-negotiation.md
core/operations.md

Various fixes thanks to @soyuka

Various doc fixes

---

core/serialization-groups-and-relations.md

See https://github.com/api-platform/docs/pull/117#issuecomment-250708465 by @teohhanhui.
Let's hope this is the one! 🙏

Fix service name with the Symfony best practices

---

core/data-providers.md
core/events.md
core/external-vocabularies.md
core/filters.md
core/form-data.md
core/fosuser-bundle.md
core/getting-started.md
core/operation-path-naming.md
core/operations.md
core/pagination.md
core/serialization-groups-and-relations.md
core/validation.md
deployment/heroku.md
distribution/index.md
schema-generator/configuration.md
schema-generator/getting-started.md

very small / detail PR to standardize the code samples throughout the doc.

standardize all code samples

---

core/getting-started.md

Also added some more example paramters. I am not sure if the xml also should be api_resource.xml?

YAML needs to be api_resource.yml not resource.yml

---

index.md
troubleshooting.md

Adding troubleshooting file for recurring questions.

Add troubleshooting

---

core/angularjs-integration.md
core/configuration.md
core/content-negotiation.md
core/data-providers.md
core/events.md
core/extending-jsonld-context.md
core/external-vocabularies.md
core/filters.md
core/form-data.md
core/fosuser-bundle.md
core/getting-started.md
core/index.md
core/nelmio-api-doc.md
core/operation-path-naming.md
core/operations.md
core/pagination.md
core/performance.md
core/security.md
core/serialization-groups-and-relations.md
core/validation.md
deployment/heroku.md
deployment/index.md
distribution/testing.md
schema-generator/configuration.md
schema-generator/getting-started.md
schema-generator/index.md

Fix pagination again

---

core/content-negotiation.md

fix  #118 by updating the content negociation doc

feat: update content negociation

---

deployment/docker.md
distribution/index.md

Removing composer install commands

feat: remove composer install

---

distribution/index.md

The command line did not have the proper spacing to be wrapped by a HTML tag pre

Fix: Page distribution

---

core/getting-started.md
core/operations.md

According to https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L291, path was wrong, my bad.

Fix path for the configuration of resources files

---

distribution/index.md

Outlined the Docker and Composer installation paths and added the commands for db initialization and server run into Composer section.

Composer installation explanation.

---

core/events.md

Update docs according to api-platform/core#882

---

core/getting-started.md

Fixed typo getting-started.md

---

distribution/testing.md

Related to https://github.com/api-platform/api-platform/issues/197

Fixes Gherkin books.feature file

---

core/configuration.md

See api-platform/core#869
(this is a new PR in exchange for #160)

Add new loader_paths option into configuration

---

distribution/index.md
troubleshooting.md

Sorry I pushed directly to the main repository without doing a PR in 2c0e644224c66428184436031d559a40e97c1f37.
This PR complete the previous commit.

Enhance docs for users of Windows

---

distribution/index.md

Dunno if the doc is outdated or if it's an mistake in the docker-compose configuration's file

fix: Update the service's name in the doc

---

core/filters.md

Documents api-platform/core#838

Add nulls comparison to OrderFilter

---

core/filters.md

@soyuka , I discover a bug when i read the docs, on the filters parts

fix minor visual bug on docs

---

core/getting-started.md

Adds XML namespace to api_platform/resources.xml file -> see api-platform/core#1080

resources.xml modifications related to PR #1080

---

core/performance.md

Fixed a typo in "performance"

---

distribution/testing.md
schema-generator/getting-started.md

Hi !
I've find an issue about docker-compose commands to execute in your documentation, the web container does not exist as it is name php :).
Regards.

[FIX] Correct doc about docker-compose commands

---

schema-generator/configuration.md

Merge @johnnypeck patches in 2.0 

---

core/configuration.md

See https://github.com/api-platform/core/pull/1271.

Add the mapping paths config

---

core/filters.md

Document api-platform/core#1333 and api-platform/core#1339

Mention whitelist on  serializer filters

---

core/filters.md

Doc PR for issue api-platform/core#1326 and PR api-platform/core#1343

Fix api-platform/core issue #1326 (DateFilter before/after filters on before or equals/after or equals)

---

core/filters.md

Update according to changes introduced in v2.1.

Update filters configuration

---

core/filters.md

Due to to bad copy/paste I've made :(

Update code example

---

core/validation.md
index.md

For https://github.com/api-platform/core/pull/1364

Add payload constraint option

---

distribution/index.md

fix https://github.com/api-platform/api-platform/issues/418

fix distribution links to parent

---

admin/authentication-support.md
admin/getting-started.md

Have corrected a few typos, updated examples to match current function signatures and clarified the source of the path used to login.

Authentication Documentation improvements

---

core/serialization.md

Fix wrong type denormalise,
Fix wrong call decorated method in supportsDenormalization,
Add class property $decorated,
Remove unused import.

Fix: Update The Serialization Process Docs.

---

core/data-providers.md

Not sure which branch to target, so 2.1 it is. I'll document how to pick a branch if you explain it to me there: https://github.com/api-platform/api-platform/blob/master/CONTRIBUTING.md or maybe this repo should have its own `CONTRIBUTING.md`, since it is not about code?

Document how to obtain a 404

---

core/index.md

https://github.com/api-platform/core/tree/master/Fixtures is not available. 
Found no Fixtures dir in the current version (master).

Update index.md - remove broken link

---

core/data-providers.md

Improved specificity of sentence

---

.travis.yml

* Use the new website
* Deploy automatically when a commit is added to `2.1`

Website autodeployment

---

admin/getting-started.md

Add some extra informations on how to set up admin and fix code as reported in http://blog.fclement.info/test-de-api-platform-et-admin.
`Using a Custom Validation Function or Inject Custom Props` still need to be tested.

Update getting-started documentation

---

core/operations.md

Related to PR [#1472](https://github.com/api-platform/core/pull/1472) on core

Add missing Symfony Routing options to operations configuration

---

deployment/heroku.md

Hello,
well... this article is really outdated and I've spent so MUCH time figure out how to make this deployement works as expected.
Luckely, I'll be the last one \o/
@dunglas I'll removed the installation of your package: once it will be tagged as stable, we may update again this article 👍

Fixed heroku tutorial for api platform 2.1+

---

.proselintrc
.travis.yml
admin/handling-relations-to-collections.md
admin/index.md
client-generator/troubleshooting.md
core/content-negotiation.md
core/data-providers.md
core/events.md
core/form-data.md
core/fosuser-bundle.md
core/index.md
core/serialization.md
deployment/heroku.md
distribution/index.md
extra/philosophy.md
index.md
schema-generator/index.md

The documentation is now automatically checked with [Proselint](https://github.com/amperser/proselint).
* `conduct.md` file is ignored because it contains [Contributor Covenant](https://www.contributor-covenant.org/): we don't want to change this text
* `heroku.md` is ignored because of a false positive: I've found no easy way to ignore false positives using proselint

Run Proselint in the CI and fix some errors

---

core/operations.md

Feat missing api receive

---

schema-generator/configuration.md

Grammar fix

---

core/pagination.md

Add docs for api-platform/core#1601

Document max items per page setting

---

core/serialization.md

I had to introduce permissions on item base so I thought I'd document this for others having the same issue :-) Maybe there's even a better way but that's how I did it and got it to work.

Added documentation for group contexts on item base

---

admin/getting-started.md

Exemple is adapted from new implementation by @mauchede ["Customize CRUD Component"](https://github.com/api-platform/admin/pull/63)

Update "Using Custom Components" section

---

core/security.md

Doc for api-platform/core#1678

Add example for access_control_message attribute

---

core/filters.md
index.md

@meyerbaptiste where are the docs for Property and Group filters?

Annotation filter doc

---

core/events.md

Since swiftmailer 6.0.0 all newInstance are removed

swiftmailler remove all newInstance

---

core/jwt.md

https://english.stackexchange.com/questions/7844/is-authentification-a-real-word

Fixed Authentification to Authentication

---

admin/getting-started.md
admin/handling-relations-to-collections.md
core/configuration.md
core/content-negotiation.md
core/data-providers.md
core/default-order.md
core/dto.md
core/events.md
core/extending-jsonld-context.md
core/extensions.md
core/external-vocabularies.md
core/filters.md
core/form-data.md
core/fosuser-bundle.md
core/getting-started.md
core/graphql.md
core/jwt.md
core/nelmio-api-doc.md
core/operation-path-naming.md
core/operations.md
core/pagination.md
core/performance.md
core/security.md
core/serialization.md
core/swagger.md
core/validation.md
deployment/heroku.md
extra/troubleshooting.md
schema-generator/configuration.md
schema-generator/getting-started.md

 Update the docs for 2.2 

---

core/filters.md

Fixes #397

---

core/graphql.md

I am working on adding more documentation in the GraphQL section.
TODO:

[WIP] GraphQL advanced features

---

core/data-providers.md

Method signature was changed before release?

Fix RestrictedDataProviderInterface code examples

---

core/filters.md

see: ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\ExistsFilter l.70

fixed small typo in Exists Filter

---

core/security.md

Escape markdown

---

extra/conduct.md

See https://github.com/symfony/symfony-docs/pull/9394/files#r172696659

Replace the "race" word in the code of conduct

---

core/pagination.md

See https://github.com/api-platform/core/pull/1779

Add doc on pagination_fetch_join_collection

---

index.md

Remove duplicated entries which lead to duplicated keys for React elements.

Update index.md - remove duplicated entries

---

core/getting-started.md

Fix broken link

---

core/filters.md

these don't seem to be needed.

remove unnessesary attributes

---

core/swagger.md

ref api-platform/api-platform#670

Remove an option that is not in 2.2

---

core/file-upload.md
index.md

WIP: Add file upload cookbook (refs #466)

---

core/file-upload.md

https://api-platform.com/docs/core/file-upload#linking-a-mediaobject-resource-to-another-resource
the property name is `image` not `cover`

update wrong property name

---

core/file-upload.md

There was a problem with content-type. A deserializer is needed.

Update file upload documentation

---

distribution/index.md

Remove inconsistent reference to database engine

---

distribution/index.md

Change failing command

---

core/graphql.md

Because it can be really useful!

[GraphQL] Add documentation about serialization groups

---

distribution/index.md

Fix link, make clickable

---

core/swagger.md

Additionally, removed the broken diff result.

--output parameter on api:swagger:export console

---

schema-generator/configuration.md

Based on [https://github.com/api-platform/schema-generator/issues/112#issuecomment-357796763](this comment) and `CardinalitiesExtractor.php`.

Add missing Field Cardinality in documentation

---

admin/authentication-support.md

The suggested code sample as is does not compile, the proposed change will.

Remove duplicate variable definition in code sample

---

core/security.md

Here's a PR which adds a YAML config on the security page as  requested: https://github.com/api-platform/api-platform/issues/785

Added yaml config to security page

---

core/swagger.md

Fixes https://github.com/api-platform/docs/issues/555

Replace incorrect SwaggerUI syntax from v1 to v2

---

.travis.yml

goes in pair with https://github.com/api-platform/website/pull/79

fix edit-on-github links

---

core/performance.md

Link to Docker setup was dead.

Fixed dead link

---

distribution/index.md

The opening brace must go on its own line

---

core/configuration.md

This pull request adds documentation for the new feature introduced in api-platform/core#2247.

Document the new show_webby option

---

core/serialization.md

see [#184 (comment)](https://github.com/api-platform/api-platform/issues/184#issuecomment-334961642)

[serializer] Mapping path when using yaml-xml

---

schema-generator/configuration.md

Fix custom schema example (moved git repo)

---

distribution/debugging.md

See https://xdebug.org/docs/all_settings#remote_connect_back for more information.

Missing configuration to connect to xdebug from VSCode

---

core/operations.md

host & schemes are not options, they are direct route attributes.

host & schemes are not options

---

core/filters.md

Are you fine with my description?

added missing DateFilter::INCLUDE_NULL_BEFORE_AND_AFTER

---

core/performance.md

Add docs for api-platform/core#2288

---

core/swagger.md

https://github.com/api-platform/core/pull/2302

Document OpenAPI v3 support

---

core/dto.md

Promote the new features introduced in 2.4

Improve the docs for DTOs

---

admin/getting-started.md

https://github.com/api-platform/admin/issues/73

fixing misunderstanding

---

core/performance.md
core/push-relations.md
core/serialization.md

https://github.com/api-platform/core/pull/2450

Add docs for HTTP/2 Server Push

---

client-generator/index.md

Fixed a typo

---

deployment/index.md

Moved to https://facebook.github.io/create-react-app/docs/deployment

Update link to create-react-app deployment doc

---

core/graphql.md

This is the docs PR for the core PR api-platform/core#2142
It adds a pagination section for graphql :)

Adding graphql pagination section

---

core/extensions.md

Use the new security helper, and various other simplifications.

Simplify the extension example

---

client-generator/typescript.md

As discussed in https://github.com/api-platform/api-platform/issues/930

Add page for typescript client generator

---

extra/releases.md

[Release] Update stable and old-stable branch

---

core/file-upload.md

Fixes https://github.com/api-platform/core/issues/2726

Add id to MediaObject entity used for file upload

---

admin/authentication-support.md
core/filters.md
core/jwt.md
core/security.md

Stop recommending the use of FOSUserBundle, among other things.
Also see https://github.com/api-platform/demo/pull/111

Improve JWT docs

---

core/serialization.md

The config file path seems wrong for the `framework` entry

Incorrect config file path

---

core/security.md

Add documentation for api-platform/core#2779 and api-platform/core#2811
fixes https://github.com/api-platform/docs/issues/814

Document the `previous_object`added in Expression Language

---

core/errors.md
core/events.md
core/file-upload.md
core/index.md
core/operations.md

Closes https://github.com/api-platform/docs/issues/804

Document toggleable listeners

---

core/file-upload.md

A rehash of api-platform/docs#831 with correct CS

Fix operator precedence

---

admin/customizing.md

Currently the doc add an empty `listFields` option, this cause a blank List view without fields.

Add a comment for the listFields option

---

distribution/index.md

The distribution is now available as a repository template! Let's advertise it.

Explain how to use the directory template

---

deployment/traefik.md

Implements  into traefik doc file
* mercure and admin declaration
* going further to define all in .env file

Update Traefik according to api-platform V2.4 docker-compose declaration

---

core/dto.md

- Fix use statements
- Fix PHP doc consistency

Fix dto.md

---

core/extensions.md

Fix typo in tag for odm autoregistration

Fix typo in tag for odm autoregistration

---

core/index.md

Reduce visibility of FOSUserBundle

---

outline.yaml

Feat: add file config nav for website for 2.1 version

---

outline.yaml

Feat: add file config nav for website for 2.2 version

---

outline.yaml

Feat: add file config nav for website for 2.3 version

---

outline.yaml

Feat: add file config nav for website for 2.4 version

---

outline.yaml

Feat: add file config nav for website for master version

---

core/filters.md

see [doctrine doc](https://github.com/doctrine/orm/pull/7838)

Fix the name of ClassMetadata

---

admin/handling-relations-to-collections.md

I forgot to add them back in #872

[admin] Add back docs for autocomplete

---

core/operations.md

Fix syntax highlight in example

---

schema-generator/configuration.md

Add exemple for feature api-platform/schema-generator#132

Add exemple for feature api-platform/schema-generator#132

---

core/data-persisters.md

Document context aware data persister interface fix #902

---

extra/releases.md

Update **Releases Process** with new stable version => 2.5

[Releases] Update stable and old-stable branch

---

core/configuration.md
core/graphql.md

Related PR: https://github.com/api-platform/core/pull/2765
@antograssiot

[GraphQL] Document the name converter and nesting separator

---

distribution/index.md

also changed HAL url to their github because the website link is broken

Updated urls to use secure links if supported

---

deployment/docker-compose.md
deployment/index.md

Documents https://github.com/api-platform/api-platform/pull/1228 and https://github.com/api-platform/api-platform/pull/1275
Closes #873

Document how to deploy with Docker Compose in production

---

distribution/index.md

| Bug fix?      | no
| New feature?  | no
| Tickets       | fixes #932 
- Add a paragaph introducing Pomm and its support for API Platform

Add entry about Pomm support

---

core/validation.md

| Bug fix?      | yes 
| Tickets       | fix #933 

Fix serialize_payload_fields config

---

core/configuration.md
core/filters.md

Provided default values should work #807

Update configuration.md default to correct work

---

.proselintrc
core/controllers.md
core/elasticsearch.md
deployment/docker-compose.md
distribution/index.md
extra/conduct.md
schema-generator/index.md

| Bug fix?      | yes 
| Tickets       | fixes #566 

Fix proselint errors

---

admin/customizing.md
admin/handling-relations-to-collections.md

Update admin documentation

---

client-generator/react.md
client-generator/troubleshooting.md
client-generator/typescript.md
client-generator/vuejs.md

Improve client generator documentation files

---

core/controllers.md
core/data-providers.md
core/deprecations.md
core/errors.md
core/events.md
core/extending.md
core/extensions.md

Fixed errors in core documentation

---

core/graphql.md

* the second part of the command was executed on the host and not in the image, thus lead to errors.
| Doc fix?      | yes

Fix command to install Graphql

---

core/filters.md

Hello,
I just fix a typo in the doc.
Cheers 😉

Fixing typo

---

distribution/index.md

| Bug fix?      | no
| New feature?  | no
| Tickets       | n/a
| Doc PR        | (this PR)
Spotted a typo, so fixed it.

Typo correction

---

core/data-providers.md
distribution/index.md

Move Pomm support section to data providers page

---

core/serialization.md

| Tickets       | none 
| Doc PR        | n/a
Related to #554 :)

Fix serialization.md: admin_input -> admin:input

---

distribution/debugging.md

Update Xdebug to 2.8.0

---

core/file-upload.md

Fix broken link in Handling file upload

---

distribution/index.md

Add missing space

---

distribution/index.md

Fix api port in distribution docs

---

admin/authentication-support.md
admin/getting-started.md

See https://github.com/api-platform/admin/issues/266.

Fix the import of hydraDataProvider

---

core/testing.md

add closing brace

---

core/file-upload.md

deprecated class fixed

---

core/validation.md

Fixed Symfony's Validation Groups outdated link

---

core/getting-started.md

Add missing information about the PATCH operation

---

core/configuration.md

updated complete configuration with right order of params and default values

updated complete configuration

---

core/pagination.md

Fixes https://github.com/api-platform/core/issues/3348

Fix the pagination_via_cursor annotation

---

client-generator/react.md

Update example for React client

---

core/jwt.md

```diff
- jwt_passhrase
+ jwt_passphrase
```

Type in a variable `jwt_passhrase`

---

core/jwt.md

Fix unsecured resource access using JWT integration

---

core/data-persisters.md

Docs show calling of function sendWelcomeMail. But function itself is named sendWelcome**Em**ail

Named sendWelcomeEmail function consistently

---

core/filters.md

Add precision about exists filter and collection association

---

core/validation.md

Add sequence validation example

---

core/jwt.md

Fixes https://github.com/api-platform/docs/issues/1067
See the detailed explanation of the issue there

Add a note on how to fix permission denied issue for JWT keys

---

core/events.md

Void return for functions

---

core/identifiers.md

Explain how to change API identifier for doctrine entities

---

core/serialization.md

Add calculated field

---

distribution/index.md

Because this explanation is in the introduction part of the guide, i considerate useful have extra tip to prevent people get stuck on the **IRI** error you get when use the original content and uses symfony flex.

Add extra tip to demo body of first `Review`

---

core/operations.md

Explain how we can expose a model that will entirely be consumed as a sub-resource/custom operation.

Exposing models without any routes.

---

client-generator/vuetify.md

Add a step-by-step description for the API-Platform distribution with docker.

Add description vuetify generator with docker

---

core/swagger.md

Add XML example

---

core/data-providers.md

added missing namespace in code sample

Fixed reference to class QueryResultItemExtensionInterface

---

core/operation-path-naming.md

Corrected the configuration path

---

core/serialization.md

- Changed incorrect URL to Doctrine primary key manual.
- Added link to Doctrine composite identifiers guide page.
- Added link to Changing Identifier in a Doctrine Entity guide page.

Improve the Serialization process guide page

---

core/configuration.md
core/mercure.md

Docs for Mercure 0.10

---

core/operations.md

tiny grammar fixes

---

core/jwt.md

SwaggerDecorator Declaration must be compatible with NormalizerInterface

jwt.md Typing method for the SwaggerDecorator

---

distribution/index.md

Fix protocol for a couple of links

---

client-generator/vuetify.md

Change "Update the scripts part of the new `composer.json`" to "Update the scripts part of the new `package.json`"

Fix vuetify generator docs

---

core/testing.md

Document findIriBy and extending the client

doc: phpunit testing API

---

core/serialization.md

serialization: fix typo on filename

---

.github/PULL_REQUEST_TEMPLATE.md

By providing a link, users don't need to search for the page, they can find it directly.

PR template: Describe what is last old-stable version

---

distribution/index.md

This PR just changes a single word. Sorry for being nitpicky here.

Improve capitalization of the PhpStorm product name

---

core/serialization.md

Fix resources.yaml example

---

core/mongodb.md

Remove note about MongoDB ObjectIds as they should work.

Remove note about ObjectIds as they should work.

---

core/data-persisters.md
core/serialization.md

feat: add more links to SymfonyCasts

---

.gitignore
extra/conduct.md
extra/contribution-guides.md
extra/enterprise.md
extra/releases.md
extra/security.md
outline.yaml

Add a security policy and Tidelift subscription

---

extra/philosophy.md

Modernize philosophy.md

---

core/operations.md

Just very minor change in doc ;-)

add missing inerface type hint on SwaggerDecorator

---

distribution/index.md

Bumped PHP version to 7.4, as per the container in v2.5.7 I've just downloaded.

Corrected PHP version number

---

core/data-providers.md
core/pagination.md

fix: Doctrine's ManagerRegistry deprecation

---

core/dto.md

Fix image in dark mode

---

core/configuration.md

Documentation for https://github.com/api-platform/core/pull/3084

add documentation for absolute_url configuration

---

core/filters.md

fix: link to SymfonyCasts in filters.md

---

core/data-persisters.md

Data Persister page - Fix typo

---

core/mercure.md

MERCURE_JWT_SECRET => MERCURE_JWT_TOKEN

Fix MERCURE_JWT_TOKEN variable name

---

core/serialization.md

Decorate a Serializer when JSON data is provided

---

distribution/testing.md

Testing the API - update command to run tests

---

core/errors.md
core/serialization.md

Update documentation to be more precise about flatten exception and how to use the new simplified decorators

Feat: Update documentation for errors and decorators

---

core/data-persisters.md

Hello,
I add a link to the Symfony Mailer documentation.

Data Persister page - add link to the Symfony Mailer doc

---

core/operations.md

Hello,
I just add `yaml` and `xml` examples.

Operations page - add yaml and xml code block

---

core/operations.md

Hello, i just updated the yaml configuration. 😉

Operations page - update YAML configuration

---

client-generator/nuxtjs.md

Added missing instructions for nuxtjs generator.

update nuxtjs.md, add missing dependencies and instructions

---

distribution/debugging.md

Upgrade Xdebug to 2.9.8

---

core/data-persisters.md

Can be seen here: https://api-platform.com/docs/core/data-persisters/#decorating-the-built-in-data-persisters

Wrong ContextAwareDataPersisterInterface use

---

core/configuration.md
core/openapi.md

https://github.com/api-platform/core/pull/3837

Configuration.md - Add 'openapi' section

---

core/controllers.md

Typo with quotes in array keys inside PHP8 attribute

---

core/messenger.md

correct type in PersonHandler example

---

core/messenger.md

Fixed typo's in Messenger doc

---

distribution/index.md

Finishes fixing https://github.com/api-platform/website/issues/221.

change patch format to diff

---

core/filters.md

Update annotations of Filters

---

admin/file-upload.md

Remove unused InputGuesser

---

core/messenger.md

No delete operations in collection

---

client-generator/vuetify.md

Update path to `pwa/Dockerfile `(formerly `client/Dockerfile`).

Update path to pwa/Dockerfile

---

core/subresources.md

In the documentation you use two point in order to assign array to api_questions_answer_get_subresource instead of arrow

Correct the subresourceOperations php8 attribute

---

client-generator/react.md

We need to specify the generator because the default is Next.

---

core/bootstrap.md
core/events.md

Related https://github.com/api-platform/core/pull/3599.

Set AddFormatListener priority to 28

---

core/jwt.md

Argon2id algorithm will be used if available

Use the “auto” password encoder and fix typos

---

core/jwt.md

Small fix api-platform/api-platform#1794

fix ArrayObject -> \ArrayObject

---

core/errors.md

Documentation for https://github.com/api-platform/core/pull/3519.

Document `exception_to_status` on resources and operations

---

core/filters.md

Add missing closing ) in annotations

---

schema-generator/configuration.md

Fix little missing updates in documentation.

Fix rdfa => vocabularies change in documentation

---

extra/security.md

Fix case on "PLatform"

---

core/identifiers.md

Add missing yaml identifiers documentation

docs: add missing yaml identifiers documentation

---

core/performance.md

Closes https://github.com/api-platform/docs/issues/1368
Following https://blackfire.io/docs/up-and-running/agent-upgrade

docs: use blackfire v2

---

core/filters.md

Add missing yaml docs in filter documentation

[docs] Add missing yaml docs in filters documentation

---

core/mercure.md

Docs to PR api-platform/core/pull/4153

feat: Add iri and urlencode functions to mercure

---

distribution/index.md

docs: fix typo

---

client-generator/vuetify.md

v-content is deprecated it should be replaced with v-main

Vuetify Generator: Fix deprecated

---

core/jwt.md

See https://symfony.com/blog/new-in-symfony-5-1-simpler-service-decoration
Closes #1418

fix: Satisfy new configuration in Symfony 5.1

---

core/data-persisters.md

To save a few seconds when copy/pasting 🙂

fix: indentation

---

core/content-negotiation.md

[Typo] Fix formats attribute name

---

core/identifiers.md

This PR fix broken links to Identifiers and update the list of supported identifers

docs: Fix broken links to Identifiers and update list

---

core/jwt.md

The authenticator manager no longer has "anonymous" security.

fix: remove anonymous option under firewall

---

core/default-order.md

fix(default-order): remove closing comment

---

core/pagination.md
core/subresources.md
core/testing.md
deployment/index.md

docs: Some typo fixes

---

admin/authentication-support.md

There is no App.js file anymore, further more the demo uses the typescript file index.tsx as included in this change.

docs: Update authentication-support.md

---

deployment/kubernetes.md

docs: Fix broken link kubernetes.md

---

core/serialization.md

fix: yaml example code of "Calculated Field"

---

core/graphql.md

fix: `graphql.md` wrong closing bracket

---

core/controllers.md

The anchor was changed to `#4-getting-the-controller-arguments`.

Fix link in controllers.md

---

.github/workflows/ci.yml
core/content-negotiation.md
core/controllers.md
core/default-order.md
core/deprecations.md
core/dto.md
core/extending-jsonld-context.md
core/filters.md
core/getting-started.md
core/identifiers.md
core/messenger.md
core/openapi.md
core/operations.md
core/security.md
core/serialization.md
core/url-generation-strategy.md
extra/troubleshooting.md

Downgrade github/super-linter to 3.17.0 because of https://github.com/github/super-linter/issues/2255

chore: update XML/YAML for 3.0 format

---

core/upgrade-guide.md

Had a few questions today, this should answer most of them :).

doc: improve ugprade guide

---

core/validation.md

feat(doc): add description of how to validate item delete operations

---

distribution/index.md

feat: modernize getting started

---

core/push-relations.md

feat: explain how to enable Server Push with Caddy

---

distribution/caddy.md
distribution/index.md
outline.yaml

feat: explain how to configure Caddy

---

core/serialization.md

Probably leftover from annotations version.

Remove closing bracket in serialization.md

---

distribution/testing.md

Change getContainer as a function instead of variable

Update testing.md: Change getContainer as function instead of variable

---

core/graphql.md

Fix convertType signature

---

core/configuration.md

https://github.com/api-platform/core/pull/4115

Fix default oauth token configuration

---

core/jwt.md

Add a missing backslash line 254

Add a missing backslash line 254 on jwt.md

---

core/jwt.md

Add missing backslash in lign 254 on Update jwt.md

---

client-generator/index.md

fix: order of generators

---

extra/releases.md

docs: new roadmap process

---

core/operations.md

Fixed typo in operations.md

---

create-client/custom.md

Very straightforward this one 😅

Typo fix in create-client/custom.md

---

create-client/react.md

Fix missing forward flag & wrong generator name

---

core/extensions.md

I just noticed this bug while copying the code to my project 🙃

Fix invalid PHP example

---

core/elasticsearch.md

Add documentation to the elasticsearch property to reflect behavior added in api-platform/core#5177

docs(elasticsearch): document the elasticsearch property

---

core/filters.md

Fixes https://github.com/api-platform/api-platform/issues/2306.

fix(filters): missing return typehint

---

distribution/index.md

Typo in distribution/index.md

---

core/graphql.md

Fixes issue https://github.com/api-platform/api-platform/issues/2292

fix: Replace Mutation with DeleteMutation in graphql docs

---

core/openapi.md

Fixes incorrect documentation as of how to use the properties for XML.

Fixes documentation related to overriding properties.

---

create-client/index.md
create-client/nextjs.md
distribution/index.md

Bootstrap has been replaced by Tailwind in the NextJS generator

---

distribution/testing.md

Use DateTimeImmutable objects in entities fixtures

---

core/identifiers.md

just a typo

---

create-client/vuejs.md

Update Vue Generator doc

---

create-client/quasar.md
create-client/vuejs.md

Update Quasar Generator doc

---

core/configuration.md
core/validation.md

In relation to PR  [#5170](https://github.com/api-platform/core/pull/5170)

feat(denormalization): add section on collecting denormalization errors

---

core/openapi.md

Fixes https://github.com/api-platform/core/issues/5388

Fix openapi documentation

---

core/user.md

setPlainPassword argument name typo

---

core/jwt.md

Since https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.17.0, the decorator is not needed anymore.

docs(jwt): remove OpenAPI decorator for the token

---

core/subresources.md

If I'm not wrong, there's an error in the specified page in the comment.

fix filename Employee.php to Company.php

---

core/filters.md

Fix comment path in Attribute class

---

core/events.md

fix: QueryParameterValidateListener event priority 16 to 2

---

core/subresources.md

"things" instead of "thinks" from  the sentence "and if we want thinks to work".

Typo in Subresources page

---

core/filters.md

Fix https://github.com/api-platform/core/issues/5403

Change ExistsFilter by the one use in v2.7

---

.github/workflows/cd.yml

Add a new deployment step > S3 Bucket. 
Deploy the static on S3 bucket in addition with Github Pages for the moment

Add deploy on bucket steps

---

.github/workflows/cd.yml

Change bucket name

---

core/events.md
core/getting-started.md
core/security.md
distribution/index.md

Also applies to branches 3.0 and 2.7

fix: broken data-persisters and data-providers links

---

distribution/index.md

fix: broken openapi link

---

deployment/docker-compose.md

Images in the "Deploying with Docker Compose" page were missing the `images/` directory.

Fix images in deployment/docker-compose.md

---

distribution/index.md

Closes https://github.com/api-platform/api-platform/issues/2490.

Better Docker commands

---

core/identifiers.md

Mention \Stringable identifier support

---

core/extensions.md

fix(docs):  update custom doctrine ORM extension example

---

core/extensions.md

Extensions - Update API Platform’s demo link

---

core/extending-jsonld-context.md
core/filters.md
core/jwt.md
core/security.md

Add missing paragraph close tags and missing code blocks on jwt file

fix: missing paragraph close tag

---

distribution/index.md
extra/troubleshooting.md

docs for FrankenPHP

---

core/mongodb.md
core/performance.md
deployment/docker-compose.md
deployment/traefik.md
distribution/debugging.md
extra/troubleshooting.md

See https://github.com/api-platform/api-platform/pull/2547.

Rename docker-compose.yml in compose.yaml

---

distribution/index.md

fix: wrong parameter for docker composer up

---

core/jwt.md

Fix symfony docs anchor edited

---

distribution/index.md

The CI lint checker was failing on this file. I think this resolves it without changing the rendered content.

Fix linter failure

---

core/graphql.md

Add documentation for GraphQL configuration with codeselector. Cf. https://github.com/api-platform/api-platform/issues/2341#issuecomment-1835939238

docs: improve GraphQL documentation with codeselector

---

core/file-upload.md
core/graphql.md
core/identifiers.md
core/serialization.md
core/state-processors.md
core/state-providers.md
core/validation.md

It's useless and too verbose for docs.

remove inheritdoc PHPDoc

---

core/controllers.md

documents https://github.com/api-platform/core/pull/6102/

feat(symfony): use_symfony_listeners enable controllers

---

core/errors.md

#1884 
Fix broken href in errors page

fix(errors): fix broken href in errors page

---

core/graphql.md

Document feature offered in api-platform/core#6120

feat(graphql): document hasNextPage in paginationInfo

---

create-client/react.md

I tried to create a client following the [current documentation](https://api-platform.com/docs/create-client/react/) and using `npm init react-app -- --template typescript my-app` but ran into a couple of problems.
I could not find the file `src/index.tsx` as in the doc but only a `src/index.js`
I first tried to convert this file into a `.tsx` file but when launching the app with `npm run` (react-scripts start) an error occured saying `Could not find a required file (index.js)`
As we created the app with the parameter `--template typescript` I think that these modifications should not be necessary and something wrong is going on
After doing the same steps with vite bundle which use the latest recommended libraries, I found out everything was going well and I had no problems setting up the …

update create-client doc for react

---

core/state-processors.md

Fix typo on state processors doc

---

core/identifiers.md

Add \Stringable as new list item

---

core/performance.md

Add Souin setup in the performance documentation.

feat(performance): add Souin setup to the documentation

---

distribution/caddy.md
distribution/index.md

The caddyfile is located in api/frankenphp/Caddyfile

Update Caddyfile path in docs

---

admin/schema.org.md

See:
- https://github.com/api-platform/docs/pull/1660 (still valid)
- https://github.com/api-platform/admin/issues/524

admin resolves schema.org semantics by iris not by types

---

core/validation.md

Fix typo in validation.md

---

core/state-processors.md

Add missing `private` to `$mailer` property.

Add missing private to mailer property

---

core/subresources.md

Add missing enable_link_security config option

Add enable_link_security

---

core/errors.md

Update doc for this change : https://github.com/api-platform/core/pull/6080/files#diff-2499cc4969d499db1106eb74f9998cfeb61379371a37adc4360aef0be5d89132R504

Error handling validation exception interface

---

core/file-upload.md

Remove processor from file upload

Remove processor from file upload

---

core/performance.md

Replace PHP-PM recommendation by FrankenPHP

---

core/filters.md

documentation about : https://github.com/api-platform/core/pull/6435

docs: security parameter

---

core/content-negotiation.md

fix: only JSON-LD is enabled by default

---

deployment/kubernetes.md

docs : Typo in Kubernetes deployment #1978

---

core/pagination.md
core/testing.md
core/url-generation-strategy.md
core/validation.md
symfony/index.md
symfony/testing.md

remove hydra:prefix

---

laravel/index.md

fix typo in `Resources`

---

laravel/index.md

Related to [this](https://github.com/api-platform/laravel/pull/4/files) Pull Request for API Platform Laravel.

Add information about publishing assets

---

core/index.md

Add mention to Laravel framework integration in `core/index.md`.

[Core > index] Add mention to Laravel framework integration

---

core/getting-started.md

Integrates Laravel parts & bootstraping the core library.
:information_source:  I've removed the demo part which was only for Symfony because it refers to the getting started variant (Symfony or Laravel). Is that OK with you or would you prefer to do things differently?

[Core > Getting Started] Integrates Laravel & bootstraping the core library

---

admin/handling-relations.md
core/angularjs-integration.md
core/errors.md
core/filters.md
core/validation.md

 remove remaining hydra: prefix 

---

laravel/index.md

fix code highlight in Laravel Docs

fix code highlight in laravel documentation

---

laravel/index.md

laravel: better GraphQL link

---

laravel/index.md

Relates to this PR: https://github.com/api-platform/core/pull/6661

[Laravel] Add Swagger Authentication Documentation

---

core/configuration.md

fix(doc): Update default values for deprecated config

---

core/filters.md

Removal of the duplicate parameters section

[Core > filters] Removal of the duplicate parameters section

---

core/upgrade-guide.md

upgrade to standalone packages

---

laravel/filters.md

Fix broken link to state providers in core documentation

[Laravel > filters] Fix broken link

---

core/operations.md

Add Laravel for operations and improve doc tips

[Core > operations] Add Laravel for operations and improve doc tips

---

core/getting-started.md

Incomplete command to runs migrations in the Laravel context & better indentation

[Core > getting started] Incomplete command & indentation

---

core/performance.md

See also: https://github.com/dunglas/frankenphp/pull/1121

fix: Dockerfile for custom FrankenPHP builds

---

core/extensions.md

fix: Fix broken link

---

laravel/index.md

https://api-platform.com/docs/laravel/#installing-laravel

docs(laravel): add missing use

---

core/filters.md

Quick fix on the doc of filters

docs: fix custom filter usage on several properties

---

LICENSE

Solves https://github.com/api-platform/docs/actions/runs/11949244587

fix: license separators

---

core/doctrine-filters.md

fix: typo in alert warning message

---

core/serialization.md

Serialization support for Laravel Eloquent & fix image

docs(serialization): support for laravel and fix image

---

core/identifiers.md

Adds compatibility with Laravel

docs(identifiers): compatibility with laravel

---

core/external-vocabularies.md

Adds compatibility with laravel

docs(external-vocabularies): compatibility with laravel

---

core/errors.md

- Supports Laravel.
- Reorganized wide lines for better readability.

docs(errors): compatibility with laravel and improve

---

core/json-schema.md

Adds Json Schema compatibility with Laravel and updates existing

docs(json-schema): compatibility with laravel and improve

---

core/openapi.md

Adds OpenAPI compatibility with Laravel and updates existing

docs(openapi): compatibility with laravel and update

---

core/url-generation-strategy.md

Adds compatibility with laravel

docs(url-generation-strategy): compatibility with laravel

---

core/mercure.md

- Supports Laravel.  
- Reorganized wide lines for better readability.

docs(mercure): compatibility with laravel and improve

---

symfony/validation.md

docs: use attribute for group sequence example

---

core/configuration.md

docs: improve configuration title

---

symfony/caddy.md
symfony/debugging.md
symfony/index.md

docs: uniformize symfony page titles

---

core/bootstrap.md

Fix typo: Bootstraping => Bootstrapping

Update bootstrap.md: Fix typo

---

core/validation.md

docs: add missing hook in validation.md for "Dynamic validation groups"

docs: add missing hook in validation.md for "Dynamic validation groups"

---

core/content-negotiation.md
core/openapi.md
core/serialization.md

Merge 4.0 into main

---

core/subresources.md

fix: code preview in 3.0 branch documentation

---

extra/releases.md

docs(releases): update information releases

---

core/filters.md

chore(filters): correct word

---

core/configuration.md

Added persistAuthorization config option. 
I was looking for this feature in the docs, but couldn't find it. After i digged deeper, i found it in the swagger ui documentation:
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#authorization
I can imagine this is a often wanted feature, promoting it in the API Platform docs may help other developers to find it easier.

docs: add swagger_ui_extra_configuration.persistAuthorization

---

core/configuration.md

add missing existing global defaults

fix: add missing global defaults

---

core/form-data.md

https://api-platform.com/docs/core/form-data/#create-your-formrequestprocessordecorator-processor

Missing space form-data.md

---

core/extensions.md

Fix missing ?Operation

---

symfony/jwt.md

Fix check path to match generated swagger url

---

symfony/index.md

Recommend the best PHP code intelligence for VSCode

---

core/filters.md

Solves https://github.com/api-platform/docs/issues/2172

fix(filters): invalid link to open api override
