api-platform/docs

- getting-started/api.md
`Then execute the generator:` was included twice
> Remove a duplicate line in `api.md`

- api-bundle/fosuser-bundle.md
FOSUserBundle doc uses ReStructuredText instead of Markdown. The link to the User entity docs was broken because of this (used `.md` instead).
> Fix link to FOSUserBundle's User class doc

- getting-started/api.md
I encountered an error while following the tutorial. I'd attempt to generate-types for the provided schema, but would get this error:
[error] The type "SocialMediaPosting" (parent of "BlogPosting") doesn't exist
As a workaround, I added the SocialMediaPosting to the types and no error, but i'm not sure if any properties need to be exposed?
> Error when following tutorial

- api-bundle/angular-integration.md
This PR adds the [selfLink](https://github.com/mgonto/restangular#using-self-reference-resources) Restangular option in order to do : 
```javascript
Restangular.all('/images').getOne(...).then(image => {
image.title = 'The new title';
image.save();
});
```
> Add selflink restangular support

- conduct.md
- index.md
To ensure the openness of the project, to show our commitment to a progressive vision of our societies and to show our strong opposition to sexism, all kinds of racism, homophobia and other forms of discriminations, I propose to add a contributor Code Of Conduct applying to all repositories under the umbrella of the [API Platform organization](https://github.com/api-platform/api-platform).
This Code Of Conduct is a verbatim copy of the [Contributor Covenant] version 1.3.0.
It's also a mark of strong support to the proposal of @ircmaxell of [adopting a Code of Conduct for PHP](https://wiki.php.net/rfc/adopt-code-of-conduct).
/cc @sroze @theofidry
> Introduce a Code Of Conduct

- core/data-providers.md
To match api-platform/core#578
> Update the data providers doc

- core/operations.md
After testing in my app I fount that:
```"special"={"special"={"route_name"="book_special"}``` Do not work
```"special"={"route_name"="book_special"}``` Work
> Incorrect call to operation reference route

- core/nelmio-api-doc.md
Following steps 1 and 2 from https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.rst is needed to get NelmioApiDocBundle installed if user started with core API. However, step 3 doesn't seem to be required (routing), and step 4 is done by API Platform docs. Could you please confirm if routing step should be skipped, or should dev still do it?
> Add steps to install NelmioApiDocBundle

- core/content-negotiation.md
Since Negotiation 2.0 this section is useless and doesn't work anymore.
> Remove "Registering a Custom Format in the Negotiation Library" section

- core/serialization-groups-and-relations.md
As mentioned in https://github.com/api-platform/docs/pull/110#issuecomment-249548709 by @teohhanhui, my previous fix was not the good way.
It's now fixed.
> Fix doc for name conversion

- core/configuration.md
Document https://github.com/api-platform/core/pull/797 in configuration
Should this be added to another chapter too?
> Exceptions to status code

- core/serialization-groups-and-relations.md
Extend the example in docs for custom serialization groups to add group only when given subject is a book. Related to #112
> [DOC] Add serialization group only when object is a book

- distribution/index.md
the link to https://api-platform.com/download is not working, I'm not sure if this endpoint should be fixed or if the link needs to be updated
> fix broken link to download

- deployment/docker.md
- distribution/index.md
- distribution/testing.md
Each time you run a docker-compose run command it will create a new container and not reuse an older one. So when the command you've run is finished the container stop but remain in memory. In order to avoid creating deads containers each time you run a command it's better to add the --rm parameter.
> Add --rm parameter to docker-compose run command examples

- core/pagination.md
Hi,
'Unrecognized option "page_parameter_name" under "api_platform.collection'; the page_parameter_name needs to sit underneath:
```
api_platform:
collection:
pagination:
page_parameter_name
```
Thanks in advance for getting this PR merged in!
Kind regards,
David
> page_parameter_name in configuration

- core/validation.md
> Add an example of dynamic validation groups

- core/filters.md
Ref https://github.com/api-platform/core/pull/964
> on|off is not supported in Boolean Filter anymore

- core/operations.md
This makes the example syntactically correct.
> Delete extra `}` in hydra context

- api-bundle/index.md
The link returns a 404. I tried to find the page on the blog to find the new link but couldn't find it.
I assume that the post was deleted.
> Remove invalid link

- core/data-providers.md
According to [https://github.com/api-platform/core/issues/1044](url)
> Add notice about custom entity identifier in data-providers.md

- core/data-providers.md
- core/operations.md
- core/pagination.md
- distribution/index.md
Correcting a few typos in the documentation. I understand those corrections should be branched off from 2.0.
> correct a few typos

- core/configuration.md
Add documentation for the configuration value that adds the possibility to customize the name of the directory where api resources can be stored.
> Add doc for 'api_resources_directory' configuration value.

- core/fosuser-bundle.md
Either the service definition should have stayed in the document or the line saying "First register the following service:" should have been removed. I went with the former. Was removed in c500601deb59085928b1b289fab40b4ce221596b.
> Change confusing reference to removed service definition. 

- core/performance.md
https://github.com/api-platform/core/pull/1297
> Eager loading force fetching the association

- core/jwt.md
Small hyperlink fix - currently, the lack of a scheme means the resultant link is rendered as https://api-platform.com/docs/core/jwt.io.
> Fixed jwt.io link

- deployment/docker.md
- distribution/index.md
- distribution/testing.md
- index.md
- schema-generator/getting-started.md
https://github.com/api-platform/api-platform/pull/407
> Update the Docker documentation

- core/validation.md
Add doc for https://github.com/api-platform/core/pull/1198
> Add use of service in dynamic validation group

- core/events.md
- core/operations.md
ActionBundle is not necessary anymore, all its feature have been introduced directly in Symfony and are enabled by default.
> Remove references to DunglasActionBundle

- core/swagger.md
Fix decorator service declaration in swagger.md
> Fix swagger.md

- core/serialization-groups-and-relations.md
- core/serialization.md
> Fix decorators config

- core/security.md
Doc says
> only admins are able to create books
But in the code, the role is `ROLE_USER` for the `POST` operation. It should be `ROLE_ADMIN`
> Fix role in code example

- client-generator/vuejs.md
in doc was missing `-g vue`options
> fixes instruction how to generate vue client

- admin/getting-started.md
The provided example does not compile correctly. With this correction it works fine.
> Correct typo in example App.js

- client-generator/react.md
Prevent this warning:
Warning: <BrowserRouter> ignores the history prop. To use a custom history, use `import { Router }` instead of `import { BrowserRouter as Router }`.
> Prevent a warning related to React Router

- client-generator/react.md
Reverts api-platform/docs#304
It prevents the warning, but it breaks the routing... Reverting for now.
> Revert "Prevent a warning related to React Router"

- core/operations.md
Refs https://github.com/api-platform/core/pull/1406
> Document requirements

- admin/authentication-support.md
Add https://github.com/api-platform/admin/pull/51 changes and change the request for compatibility with LexikJWTAuthenticationBundle (tested and works)
> Update admin authentification

- index.md
They were removed in
https://github.com/api-platform/api-platform/commit/d2a9272a610013671ffc3215c1c65e79b1c496c8
> Remove links to removed resources

- core/jwt.md
The diff would be easier to read if you capped lines to some limit (120 chars?). Consider it.
> Proofread jwt

- core/configuration.md
I don't know where comes this key from. But it looks like this is not valid with api-platform...
> Removed non existing configuration key

- core/swagger.md
When copying/pasting the annotation from the current doc we got ```[Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_IDENTIFIER, got 'attributes' at position 48 in property AppBundle\Entity\UserPortfolioAudit::$pfType.``` because attributes should not be quoted.
> Swagger ApiProperty variable should not be quoted

- core/operations.md
Related to this PR https://github.com/api-platform/core/pull/1520
Add maxDepth parameter on ApiSubresource in order to control the depth of subresources.
> add maxDepth on subresources doc

- core/serialization.md
When decorated the serializer is not set in the .inner service  anymore ?
Adding the SerializerAwareInterface on the decorator and passing serializer to the decorated one solve the problem.
> Fix missing serializer in decorated normalizer

- extra/philosophy.md
Fixes links which currently lead to 404 pages. 
Replaces Angular js link with the link to Client Generator docs.
> Fix 404 links on API Platform's Philosophy

- distribution/index.md
The comment is for the `AppBundle\Entity\Review` class. :koala:
> Change comment text to refer to correct file name

- core/dto.md
- index.md
Fixed https://github.com/api-platform/core/issues/1590
> Added basic doc for dealing with DTO

- core/swagger.md
ref: https://github.com/api-platform/core/pull/1607
> [Swagger] Doc: Changing the name of a definition

- core/operations.md
Fixes https://github.com/api-platform/core/issues/1596
> Doc. how to change the path of a subresource

- core/swagger.md
This adds some documentation on how to keep the api on one endpoint, and move swagger ui to a different one.
> Documenting how to have swagger on custom uri

- core/jwt.md
Using this configuration is not the recommended way anymore. It triggers 4 deprecation including `"lexik_jwt_authentication.security.authentication.entry_point.main" service is deprecated`
> Update LexikJWTAuthenticationBundle configuration

- extra/releases.md
- index.md
The important part:
* **stable** (currently the **2.2** branch): regular bug fixes are integrated in this version
* **old-stable** (currently **2.1** branch): security fixes are integrated in this version, regular bug fixes are **not** backported in it
* **development** (**master** branch): new features target this branch
Older versions (1.x, 2.0...) **are not maintained**. If you still use them, you must upgrade as soon as possible.
ping @api-platform/core-team
> Document the release policy

- core/performance.md
See: https://github.com/api-platform/api-platform/issues/580
> Extending Cache-Tags docs for varnish

- core/operations.md
Users sometimes create custom collection operation and add it as first item of collectionOperation but dont do that with the intention to overwrite the default resource Class IRI. If the route path contains custom route params this results in an error though and debugging it is quite hard (need do make your way down into IriConverter to discover the custom route is used for router).
> Describe the fact that first GET collectionOperation is used for resourceClass IRI

- core/swagger.md
> The following configuration will provide additional context to your Swagger definitions
- In api-platform ^2.1 this is not the case. Defining a custom `swagger_context` has the effect of wiping out any default documentation. Therefore this wasn't being treated as "additional context" and should not be referred as such.
> docker-compose exe php
- Fixed the wrong docker compose command "exe" instead of "exec".
> Minor changes to the Swagger documentation page

- core/operations.md
Document api-platform/core#1732
> Document easier custom operation definition

- core/swagger.md
Related to https://github.com/api-platform/core/pull/1697
> Add documentation for Swagger doc with api_gateway query parameter

- core/filters.md
Originally references the RangeFilter when it should be the OrderFilter.
> Fix reference to wrong Doctrine namespace.

- core/form-data.md
Using DI decorator in https://api-platform.com/docs/core/form-data/, in order to decorate the original DeserializeListener.
> core/form-data.md: use dependency injection decorator feature

- core/filters.md
Hi,
This is a proposal to add an example on the date filter and change some usages example, for consistency, with the (already used) syntax : `<choice1|choice2|choice3>`
> Filters - consistency on usage example + date example

- schema-generator/getting-started.md
> “Schema generator“ > improve “Getting started”

- admin/getting-started.md
admin-on-rest has moved react and react-dom to its **dev** dependencies since https://github.com/marmelab/admin-on-rest/commit/9836464ca275b1fbf84d932e27b4d7f3fb35d374#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L66
Following this step from the getting-started guide leads to compilation error (module missing from node_modules)
> Remove obsolete informations

- core/operations.md
While trying the recommended custom operation configuration from the documentation, I found out that the attribute `method` seems to be mandatory.
> Fix documentation for custom operation configuration

- core/configuration.md
Following the PR [#1699](https://github.com/api-platform/core/pull/1699), I updated the doc to add the request_option parameter.
As a reminder,  the request_options parameter allows to pass options to the client charged with the BAN request.
> Updated the configuration.md file for the request_options parameter

- core/getting-started.md
Hi,
The phpdoc of the variable $name was [@]param instead of [@]var. (Other variables don't have it, so i decide to remove it)
http://docs.phpdoc.org/references/phpdoc/tags/param.html
And add the phpdoc to removeOffer.
> Update getting-started.md - update phpdoc

- core/filters.md
- core/graphql.md
Follows https://github.com/api-platform/core/pull/1868
> Describe how to filter on nested properties with GraphQL

- admin/getting-started.md
This PR adds a note about particular requirements that need to be met when creating Admin without Docker.
Based on discussion from an issue here: https://github.com/api-platform/admin/issues/73 and SO discussion: https://stackoverflow.com/questions/50394139/unable-to-retrieve-api-documentation-on-admin-of-api-platform.
Otherwise the issue is rather hard to pinpoint without digging into CORS and checking requests and responses. Neither HydraAdmin nor anything else complains about anything. Console is empty in this case either. Just the dreaded: “Unable to retrieve API documentation”.
> Add expose-headers note

- distribution/testing.md
Since it is no longer part of the standard distribution the Behat BDD library needs to be installed before you can proceed with the documented usage.
> Update docmentation about Behat

- distribution/index.md
So, as a user, I don't see the Symfony welcome page.
> Add a note about the `/api/` prefix

- core/content-negotiation.md
- core/swagger.md
This is the doc PR for https://github.com/api-platform/core/pull/1798 in 2.3
> Add documentation on enabling format for specific operation

- core/events.md
The event constant table listed the `PRE_SERIALIZE` and `POST_SERIALIZE` as constants for the `kernel.request` event. The correct event for those constants should be `kernel.view`.
> Fixed the event constant table

- core/errors.md
Hi,
So I made a new PR with the correct branch (2.2).
It fixes the example that doesn't work because the `KernelEvents::REQUEST` returns a `GetResponseEvent` instead of the required `GetResponseForControllerResultEvent`.
So as suggested in the issue #424 it's changed to the first hook available in `KernelEvents::VIEW` to get a `GetResponseForControllerResultEvent` : `PRE_VALIDATE`.
> Fixes #424 - Wrong Kernel Event / EventPriorities in Errors Example

- core/fosuser-bundle.md
- core/graphql.md
- core/operations.md
- core/serialization.md
- core/swagger.md
Doc for api-platform/core#1788.
> Document and use the new short attributes syntax

- core/operations.md
It needs to be either
```
@ApiResource(attributes={"route_prefix"="/library"})
```
or 
```
@ApiResource(routePrefix="/library")
```
to work correctly.
> Fix routePrefix documentation

- core/default-order.md
Seems like this is a copy paste error. This sentence describes `order`, not `filter`.
> Copy paste error fix: filter -> order

- core/filters.md
Seems like it is parsed incorrectly and looks bad in documentation:
After this update, it will look just fine (like a code example)
> Fix formatting of DQL query

- core/serialization.md
Seems like a word `many` is missed in this sentence
```diff
- You can create as relation embedding levels as you want.
+ You can create as many relation embedding levels as you want.
```
> Add missing word

- core/serialization.md
I made some changes to the serialization documentation for clarity, grammar, and style.  There were also a few typos that I corrected.
If you think this is a worthwhile PR, I would be happy to provide suggestions for some of the other pages in the documentation as well.
> Clarity, grammer, and style changes to serialization docs

- core/serialization.md
The serialization documentation section `Changing the Serialization Context Dynamically` defines a serialization group as `admin:input` in the entity exampe, however it was being added as `admin_input` in the `BookContextBuilder` example.
i.e. changed from:
```
$context['groups'][] = 'admin_input';
```
to:
```
$context['groups'][] = 'admin:input';
```
> Corrected typo in BookContextBuilder example: admin_input vs admin:input

- core/serialization.md
The serialization groups section mentions "You can also use the YAML configuration format", but only shows the API Platform portion of the YAML format.
For developers choosing to define everything in YAML, they also need the `/config/serialization/Book.yaml` file to be defined.
In other discussions I've read on the subject, it's mentioned that the serialization component is already  documented elsewhere. I think it's important to deliver the config on a silver platter so there is nothing left for interpretation which may take the developer down a rabbit hole.
> Added serialization config to complete the YAML format example.

- core/operations.md
Unfortunately, we discovered that Subresources work only for `GET` operation too late, after creating entities and debugging the code.
It would save some time for developers who will know it from reading the documentation rather than creating the real code that there is a limitation at the moment.
BTW, are you planning to support `POST`/`PUT`/etc. for sub resources?
> Add note about GET operation for subresources

- core/getting-started.md
there's a whitespace causing the link for __'the Symfony Serializer's configuration files or annotations.'__ to be rendered not absolute on api-platform.com. github is more forgiving so the link works here when rendered as markdown. 
See broken link: https://api-platform.com/docs/core/getting-started
> Getting Started external link broken

- core/operations.md
The information about necessity that the `__invoke()` method’s parameter must be called `$data` was easy to miss in the large amount of information. This proposal makes it more visible by putting it in its own paragraph and by writing it in bold.
> Custom operation: enhancing the visibility of an important remark

- admin/getting-started.md
RichTextInput is not part of react-admin. Import from ra-input-rich-text instead.
> RichTextInput is not part of react-admin.

- core/debugging.md
> Add debugging section to the core manual

- core/serialization.md
There are several implementations of `LogicException`, I chose to take the one from PHP core.
See #594
> Fix imports in BookAttributeNormalizer

- client-generator/react.md
1. change ReactDom to ReactDOM https://stackoverflow.com/questions/33125669/uncaught-referenceerror-reactdom-is-not-defined
2. change foo to book
3. add bash code block
> fix not working code

- distribution/index.md
Fix issue https://github.com/api-platform/docs/issues/602 
Following the instructions on the GraphQL part, the route ```/graphql``` is not found after requiring graphql-php. So I added the cache:clear command in order to fix it.
> Add the cache clear command to the Graphql section

- .travis.yml
`yarn` is not installed by Travis because there is no `yarn.lock` or `package.json`.
> Install yarn in before_install

- core/operations.md
PR for adding the access control on path annotation.
refer to https://github.com/api-platform/docs/issues/461
> #461 - Add access control example 

- core/filters.md
#601 - Add note for usage of multiple value search in Filters
> #601 - Add note for usage of multiple value search in Filters

- core/filters.md
Linked to this [issue](https://github.com/api-platform/api-platform/issues/871)
> Issue 871: fix entityManager type

- core/operations.md
Given, the following entities:
```php
/**
* @ApiResource(subresourceOperations={
*     "quizzes_get_subresource"={
*         "access_control"="is_granted('ROLE_ADMIN')"
*     }
* })
*/
class User
{
// ...
/**
* @ApiSubresource
*/
private $quizzes;
}
```
```php
/**
* @ApiResource
*/
class UserQuiz
```
Requesting `/users/{id}/quizzes` should be restricted to `ROLE_ADMIN` users, but anybody can access it. After some searches, the `access_control` option must be declared in the `subresourceOperations` key in the subresource.
> Fix typo on subresourceOperations.access_control

- core/fosuser-bundle.md
this is to not use the default protected word User for an sql table https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#a-doctrine-orm-user-class
> add @ORM\Table(name="fos_user") to user entity

- core/content-negotiation.md
It seems that showcasing annotation is not always enough, users sometime struggle with YAML or XML.
This might help...
> Fixes api-platform/api-platform#884

- core/serialization.md
> Add a yaml example for specifying an identifier.

- core/pagination.md
Many are missing examples how to use pagination with custom controllers.
This could help.
> Examples for custom controllers

- core/performance.md
Documented setting up Blackfire.io for profiling.
Not sure how/whether any indexes need updating with the inclusion?  Please advise.
> Details on how to set up Blackfire.io profiling

- core/security.md
Add sentence to redirect to extension to restrict a collection
> Update security doc

- admin/getting-started.md
Added information about how to build Admin app on top of react-admin's Admin component,
and show example of usage custom components for create, edit, show and list actions.
> Added example usage of react-admin Admin component

- core/serialization.md
I was implementing this example today and I noticed that it is possible to use `NormalizerAwareInterface` instead of `SerializerAwareInterface`. By using the first interface and corresponding trait, the `instanceof NormalizerInterface` check is no longer needed.
I also shortened the constant (for readability) and removed the now quite small `passOn` method to use the code inside directly in the `normalize` method.
> Less complex normalizer

- core/operations.md
`<group>` is invalid, it throws an XML Validation exception
```
ERROR 1871] Element '{https://api-platform.com/schema/metadata}group': This element is not expected.
```
> Fix XML Mapping for normalization_context groups

- core/dto.md
https://github.com/api-platform/core/pull/2235 ping @silverbackdan
> Document input/output resource attribute

- core/deprecations.md
Docs for https://github.com/api-platform/core/pull/2252 (ping @blanky0230).
> Add docs for the Sunset HTTP header

- admin/getting-started.md
While not clear in existing docs, this PR illuminates a simple strategy for iterating over unserialized array input components.
> provide approach for unserialized array inputs

- core/identifiers.md
With the @type tag, there is the error 
```
[Semantical Error] The annotation "@type" in property App\Entity\Person::$code was never imported. Did you maybe forget to add a "use" statement for this annotation?
```
> Replace @type tag by @var tag in the phpdoc

- core/filters.md
in previous example, offer dont has a name field, but have description.
description's (or name) filter type is partial then it can not get multi value and filter with them.
> name field is not defined in offer

- core/data-providers.md
Error: `Warning: Illegal string offset id`
Full response:
```
{
"@context": "/api/contexts/Error",
"@type": "hydra:Error",
"hydra:title": "An error occurred",
"hydra:description": "Warning: Illegal string offset 'id'",
"trace": [
{
"namespace": "",
"short_class": "",
"class": "",
"type": "",
"function": "",
"file": "/usr/local/src/app/vendor/tienvx/mbt-api-bundle/src/DataProvider/ModelDataProvider.php",
"line": 53,
"args": []
},
{
"namespace": "Tienvx\\Bundle\\MbtApiBundle\\DataProvider",
"short_class": "ModelDataProvider",
"class": "Tienvx\\Bundle\\MbtApiBundle\\DataProvider\\ModelDataProvider",
"type": "->",
"function": "getItem",
"file": "/usr/local/src/app/vendor/api-platform/core/src/DataProvider/ChainItemDataProvider.php",
"line": 57,
"args": [
[
"string", …
```
> Fix wrong identifier

- core/form-data.md
Solving #690 
According to https://github.com/symfony/http-foundation/blob/master/Request.php#L1429, `isMethodSafe` should be passed `false` as an argument.
> Call Request::isMethodSafe(false) instead of Request::isMethodSafe()

- admin/getting-started.md
Must've been forgotten:
- `import { RichTextField } from 'react-admin';` is imported but never actually used
- "The `field` property of the `Field` class allows to set the component used to render a property in list and show screens." - however, the field property is never set
Code was validated to work.
> [ADMIN] Add missing code in example

- core/graphql.md
- distribution/index.md
To be in sync with the URL of the distribution
> GraphQL: use the default port

- core/filters.md
Fix error in https://api-platform.com/docs/core/filters#numeric-filter (text is same as boolean filters)
> Fix error in filters documentation

- core/filters.md
Based on a conversation in Slack I found out that extractProperties is not supported anymore. Using the code in the documentation will do nothing.
> Removal of deprecated extractProperties method in docs

- distribution/index.md
When installing API Platform via Symfony Flex and Composer on an Apache or Nginx server, the rewrite rules need to be enabled or you'll get a lot of 404 errors. I've added a line of information and the link to the official Symfony documentation with all the relevant information.
> Added Symfony rewrite rules link

- core/errors.md
The name of the class is `CartManager` so I renamed `ProductManager.php` to `CartManager.php`
> Wrong exemple file name

- core/configuration.md
Adds `allow_plain_identifiers` option to configuration reference.
> Add missing allow_plain_identifiers option to conf reference

- core/identifiers.md
The document says to tag the service with  `api_platform.identifier.normalizer` but this should be `api_platform.identifier.denormalizer` in order to work correctly.
> Invalid tag: normalizer should be denormalizer

- core/getting-started.md
- core/serialization.md
The serialization part of the "getting started" section was partial and unuseful. I think it has been moved some time ago but every time I need to find the (de)normalization context, I'm confused by the getting started page !
I replaced it by a link to the serialization page moved the useful links on argument passed to `serialize` / `deserialize` function in the serialization page.
Thanks
> Clean serialization incomplete informations from getting started section

- core/getting-started.md
- distribution/index.md
When API Platform is installed, an argument for Symfony MakerBundle's `make:entity` command is added to add some default configurations for API resources.
It looks like this tip is not documented, so this PR adds this information to the _Getting Started_ page.
> Add a tip to use MakerBundle to create resources

- core/performance.md
thanks for the reminder @bendavies :D see https://github.com/api-platform/core/pull/1725#issuecomment-464358729
> Document metadata cache parameter

- core/performance.md
The way the installtion is setup permissions for */tmp* would be changed.
Making a subdirectory and performing installation there is also the recommended way on the official page: 
https://blackfire.io/docs/integrations/docker
Fun Fact: Installing blackfire the old way breaks some api-platform installations as big requests can't be buffered in /tmp anymore.
> Fix blackfire installation documentation

- admin/getting-started.md
As mentioned in the issue https://github.com/api-platform/admin/issues/146, the code proposed in the documention to handle file upload is not fully working.  
In this PR, I removed the useless `<FunctionField>` component. Indeed, I see no interest using it.
Other modifications don't require to be explained (minor fixes such as `value` instead of `value[0]`).  
---
Nevertheless, the following lines (picked from the doc) need to be discussed :  
```javascript  
field.normalizeData = value => {  
if (value[0] && value[0].rawFile instanceof File) {  
const body = new FormData();  
body.append('file', value[0].rawFile);  
return fetch(`${entrypoint}/images/upload`, { body, method: 'POST' })  
.then(response => response.json());  
}  
return value.src;  
};  
``` 
This part of code is …
> Fix bugs in Managing Files and Images code

- core/filters.md
I don't know if this example is very good but it works like a charm in my case and I use it. 
Maybe @meyerbaptiste can have a look :+1:
> Add example for the Custom ElasticSearch Filter

- core/configuration.md
- core/filters.md
This PR documents the new `ExistsFilter` behavior proposed in the pull request api-platform/core#2243.
> Update the ExistsFilter behavior

- core/filters.md
When using `ApiFilter` annotation, it seems that you have to set the concerned properties in the annotation itself.
> Custom filter on specific properties using ApiFilter annotation

- core/operations.md
If we keep `method: 'GET'` the result will be an additional unexpected route.
In fact, serialization will work as expected, but a new route will be created (a classic collection route on subresource, wich is not expected, specially when you create a subresource path).
I hope i do not misunderstand the implementation.
> remove useless example

- core/performance.md
Reverts api-platform/docs#766
Related: https://github.com/api-platform/core/pull/2648
See discussion in https://github.com/api-platform/core/issues/2644
> Revert "Remove mention of deprecated "api_platform.metadata_cache" parameter"

- core/pagination.md
See https://github.com/api-platform/core/pull/2639
> Rewrite the section on Doctrine ORM Paginator

- core/operations.md
We have just upgraded a big app from `2.3.6` to `2.4.2` and I think documentation is incorrect for subResources.
Without these changes, our tests were failing
1. First of all, I think the new behavior in `2.4.2` is a BC break, because it *did* work before, but doesn't work after upgrading
2. What we did is just replaced `collectionOperations` with `subresourceOperations`, pleasee see the simplified diff
```diff
- collectionOperations:
+ subresourceOperations:
api_services_service_products_get_subresource:
normalization_context:
groups: [...]
```
Why doesn't it work in `2.4.2` anymore?
Because the following code expects sub resources' configuration to be under `subresourceOperations` key:
https://github.com/api-platform/core/blob/ef76e6bc20ca0658a28c5ccccc1b406f47dbbec3/src/Metadata/Resourc …
> Fix incorrect docs for subresource operations

- distribution/debugging.md
Xdebug 2.7.0 add compatibility with PHP 7.1+ (7.1, 7.2, 7.3).
> Update Xdebug for PHP 7.3 compatibility

- admin/getting-started.md
- core/validation.md
By default, without more information, the admin shows IRIs for entities.
This makes it really hard for actual users to parse the information, especially when seeing relations this way. This is an attempt to document how to solve the problem marking the property with Schema.org (thanks @GregoireHebert for the tip in the first place)
> Include information on how to show names instead of IRIs for entities

- admin/authentication-support.md
Related issue : https://github.com/api-platform/admin/issues/165
ATM, using the latest version of the admin with the current documentation lead to this error when there is no token in the local storage :
```js
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
in Switch (created by RoutesWithLayout)
in RoutesWithLayout (created by Route)
in div (created by Layout)
in main (created by Layout)
in div (created by Layout)
in div (created by Layout)
in Layout (created by WithStyles(Layout))
in WithStyles(Layout) (created by Route)
in Route (created by …
```
> Fix Admin Authentication Support

- core/mercure.md
The current doc of Mercure's usage with API Platform states that we need to create three variables in the `.env` file in order to enable pushing to the Hub: `MERCURE_PUBLISH_URL`, `MERCURE_SUBSCRIBE_URL` and `MERCURE_JWT`. But the last one is not correct, and must actually be named `MERCURE_JWT_SECRET`.
> Mercure: fix an error in an environment variable name

- distribution/debugging.md
[2019-05-06] — Xdebug 2.7.2
Fixed Bugs
Fixed bug #1488: Rewrite DBGp 'property_set' to always use eval
Fixed bug #1586: error_reporting()'s return value is incorrect during debugger's 'eval' command
Fixed bug #1615: Turn off Zend OPcache when remote debugger is turned on
Fixed bug #1656: remote_connect_back alters header if multiple values are present
Fixed bug #1662: __debugInfo should not be used for user-defined classes
> Update Xdebug to 2.7.2

- deployment/heroku.md
This is to make it consistent with the project name created with the first command
> Correct the project directory from api to bookshop-api the example project 

- client-generator/index.md
- client-generator/quasar.md
Hi, 
Added docs for https://github.com/api-platform/client-generator/pull/134
I hope the branch is the right one.
> Add quasar framework docs for generator.

- core/events.md
Since Symfony 4.3, this class is deprecated.
source: https://github.com/symfony/symfony/blob/4.3/src/Symfony/Component/HttpKernel/Event/GetResponseForControllerResultEvent.php#L18
> Event: GetResponseForControllerResultEvent is deprecated

- core/operations.md
Text reference to injected service ($myService) doesn't match the service injected in the code snippet. (BookPublishingHandler $bookPublishingHandler)
> Wrong injected service referenced

- client-generator/react.md
Update import of `history` package to avoid the following error:
```
Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.
```
> Update import of `history` package

- schema-generator/getting-started.md
To corresponding to the example given on the related PHP class part, the ```enum``` type ```OfferItemCondition``` needs to have:
```yaml
properties: {}
```
> fix enum type without properties

- core/graphql.md
Updating docs for this pull request:
https://github.com/api-platform/core/pull/3015
> [GraphQL] Different security and serialization for item_query and collection_query

- core/performance.md
> Add docs for api-platform/core#2758

- core/testing.md
- distribution/index.md
- distribution/testing.md
Docs for:
* https://github.com/api-platform/core/pull/2608
* https://github.com/api-platform/core/pull/2887
* https://github.com/api-platform/core/pull/3003
* https://github.com/api-platform/core/pull/2940
See also the PR on the demo app: https://github.com/api-platform/demo/pull/129
> ApiTestCase and assertions docs

- core/errors.md
`Using a string "HTTP_BAD_REQUEST" as a constant of the "Symfony\Component\HttpFoundation\Response" class is deprecated since API Platform 2.1 and will not be possible anymore in API Platform 3. Use the Symfony's custom YAML extension for PHP constants instead (i.e. "!php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST").`
> Use yaml const to not create a deprecation message

- admin/getting-started.md
- client-generator/nextjs.md
- client-generator/react-native.md
- client-generator/react.md
- client-generator/typescript.md
- core/data-persisters.md
- core/data-providers.md
- core/deprecations.md
- core/design.md
- core/errors.md
- core/external-vocabularies.md
- core/filters.md
- core/getting-started.md
- core/graphql.md
- core/index.md
- core/pagination.md
- core/swagger.md
- core/testing.md
- core/validation.md
- deployment/heroku.md
- deployment/kubernetes.md
- distribution/index.md
- extra/philosophy.md
- extra/troubleshooting.md
- schema-generator/getting-started.md
- schema-generator/index.md
Varios docs improvements.
P.S. Have I made changes to the proper branch?
> Improve docs

- core/security.md
It took me a while to figure out that I had to give the object into my `is_granted()` expression. Maybe it could be added to the documentation to save time for new users like me.
> Add precisions on the custom permission

- core/file-upload.md
Current version of this page matches OAS2 specifications while the API Platform Distribution uses OAS3.
> Update File Upload page to match OAS3 specs

- core/performance.md
| Tickets       | fixes #940  
I'm not sure if I should also document `fetchPartial` attribute at the resource level and provide an example.
> fetchPartial documentation

- core/security.md
| Bug fix?      | yes (documentation bug)
| New feature?  | no
| Tickets       | None
| Doc PR        | N/a
I believe the key should be `security` instead of `security_`.
> Fix wrong key name in Yaml example for adding security

- core/dto.md
The documentation about using DTOs only shows `input` and `output` attributes at the resource configuration level. This is a bit misleading because one might think only one input DTO and only one output DTO are supported, while they can be different for each operation.
> Document per operation DTO usage

- extra/philosophy.md
| Bug fix?      | yes
| Tickets       | n/a 
Fix some typos.
> Fix spelling

- core/file-upload.md
- core/graphql.md
For: https://github.com/api-platform/core/pull/3041
Taken from: https://github.com/api-platform/docs/pull/913, thank you @lukasluecke!
> [GraphQL] Document file upload

- core/file-upload.md
| Bug fix?      | no
| New feature?  | no
| Tickets       | -
When someone uploads a file with an already existing name it overwrites the existing file. Easily prevented by providing this configuration.
> Prevent uploaded files from being overwritten

- client-generator/vuetify.md
| Bug fix?      | no
| New feature?  | yes
| Tickets       | 
| Doc PR        |
> Vuetify doc

- client-generator/troubleshooting.md
When running API Platform on development servers without valid TLS `client-generator` cannot generate client/interfaces because fetch is rejected.
> added note about NODE_TLS_REJECT_UNAUTHORIZED to Troubleshooting

- core/messenger.md
When using Messenger integration, the current documentation specifies :
- use `output=false` to return blank response
- remove `output=false` if you want to return Data returned by your MessageHandler
However, no information is given on situation where multiple handlers are handling the same message.
- if the last handler returns void and resource configuration specifies that an output must be generated, a `No item route associated with the type` error is thrown due to the absence of any `GET` item operation configuration on the resource
- Ensuring that the handler returning data to be returned in the HTTP response process the message last solves this issue
> [Messenger] Add information about multiple handlers return value

- core/subresources.md
The current documentation mentions that:
```In the previous examples, the method attribute is mandatory, because the operation name doesn't match a supported HTTP method.```
Yet, the method attribute was missing in the YAML example.
> Add missing method attribute for YAML example

- core/subresources.md
Currently the route name is used as the operation name, which is not ideal, but it is what it is.
> Fix wrong operation name for subresource operation

- distribution/index.md
The list of services was out of date:
- Add Vulcain in the services list
- Update the opened ports
> Fix the list of services and their ports on the Distribution page

- core/swagger.md
add comment to use openapi_context attribute when using openapi V3 specification
> add comment to use openapi_context

- admin/authentication-support.md
without the return statement JS throws an error: 
> Expected an assignment or function call and instead saw an expression  no-unused-expressions
this commit fixes this issue
> add missing return statement in JS code

- core/validation.md
Documentation for https://github.com/api-platform/core/pull/3329
> Add specification property field's values restrictions based on validation constraints 

- core/dto.md
Currently it is not quite clear that serialization group annotations should be used on classes used for data transformation. At least not explicitly. See the note for inclusion proposal.
> Note about serialization groups related to DTO

- distribution/debugging.md
XDEBUG_VERSION=2.7.2 is not compatible with php 7.4 and therefore has to be a higher version for api-platform 2.5.4
> Update xdebug installation guide

- core/controllers.md
There is a sentence:
> The distribution of API Platform also eases the implementation of the ADR pattern: it automatically registers action classes
stored in `api/src/App/Controller` as autowired services.
However, all the examples below this sentence use controllers located in `src/Controller` (https://api-platform.com/docs/core/controllers/).
Hence the change - removing the `App` folder in path to action classes.
Moreover, there is no path `api/src/App` in `api-platform/api-platform` distribution.
> Remove `App` prefix in path to action classes

- core/form-data.md
User Deprecated: Passing arguments to "Symfony\Component\HttpFoundation\Request::isMethodSafe()" has been deprecated since Symfony 4.4; use "Symfony\Component\HttpFoundation\Request::isMethodCacheable()" to check if the method is cacheable instead.
> isMethodSafe() has been deprecated Symfony 4.4

- core/extensions.md
Markdown makes service name cursive
> Avoid applying markdown syntaxt for service names

- core/extensions.md
For some reason, passing `User` object to `setParameter` in extension leads to incorrect query:
```sql
SELECT s0_.id AS id_0, s0_.title AS title_1, s0_.image_id AS image_id_2, s0_.user_id AS user_id_3 
FROM sound_record s0_ 
WHERE s0_.id = 1 
AND s0_.user_id = 0;
```
note `user_id = 0`.
After changing `$user` to `$user->getId()`, everything works as expected:
> User integer user ID instead of passing a User object to Doctrine Query

- core/file-upload.md
Just a little patch to replace the deprecated attribute `access_control` with `security`. Don't know if the patch should target this branch or master. Let me know if I need to change.
> Use `security` attribute instead of deprecated `access_control`

- core/file-upload.md
Conform to this article, the "GetResponseForControllerResultEvent " has been renamed to "ViewEvent" for Symfony 4.3 +
https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching#updated-httpkernel-event-classes
> Update file-upload.md for Symfony 4.3+

- core/dto.md
Adding an id to Book entity class and with the annotations included the example works from scratch including OpenAPI docs.
> Add mandatory id and annotations

- core/operations.md
This link doesn't work in the current documentation.
> typo: link to #overriding-the-openapi-specification

- client-generator/react-native.md
React-native-router-flux has sub dependencies that are not currently being installed. As of npm@3, neither yarn nor npm install sub dependencies by default.
If a new user is not familiar with the "has unmet peer dependency" warning and fails to install the listed sub dependencies, then expo will fail with errors. By adding the sub dependencies onto the existing yarn command then the new user will have one less thing to troubleshoot.
> Install react-native-router-flux sub dependencies

- core/security.md
Feature : https://github.com/api-platform/core/pull/3227
> [Serializer] Add documentation on ApiProperty security attribute

- core/jwt.md
Whilst acl is installed in the API Platform docker setup, users may need to install it in their own environment
> Added note about acl dependency

- core/validation.md
The current docs state that to serialize ALL payload fields, use `serialize_payload_fields: []`
Actually, this means NONE of the payload fields are serialized.
The default value, to serialize ALL payload fields, should be `serialize_payload_fields: ~`
> Fix incorrect serialize_payload_fields default

- core/data-persisters.md
If the decorated DataPersister is from type `DataPersisterInterface` there is no `$context` argument.
Alternatively we could stay with `DataPersisterInterface` and remove the `$context` argument in `supports()`, `persist()` and `remove()`
> Change Interface of decorated DataPersister

- core/graphql.md
It was not mentioned in the docs, so I thought it may be useful for other developers.
I tried to stick to the structure of the docs, more-or-less copying the existing [changing-the-location-of-swagger-ui](https://api-platform.com/docs/core/swagger/#changing-the-location-of-swagger-ui).
This is my first contribution to Api Platform docs, so please feel free to correct or improve my proposal.
> Add how to change the GraphQL entrypoint URL

- core/serialization.md
Just fix bad indentation in `core` -> `serialization` -> `Calculated Field` -> `getSum()` method !
> fix serialization getSum() bad indentation

- core/operations.md
This simply adds php formatting to a codeblock that was missing it
> Fix markdown codeblock formatting

- admin/handling-relations.md
As per the [ReferenceField](https://marmelab.com/react-admin/Fields.html) description, React Admin needs the Resource for the referenced resource to be declared in the app to be able to get the data:
```
Note: You must add a <Resource> for the reference resource - react-admin needs it to fetch the reference data. You can omit the list prop in this reference if you want to hide it in the sidebar menu.
```
> A RessourceGuesser was missing in on of the examples

- core/identifiers.md
Hi there
First time here
This PR fixes two missing ApiProperty uses in the identifiers documentation.
I got caught by this during testing the examples few hours ago.
Hope it helps
> Missing ApiProperty uses in identifiers doc

- core/filters.md
> fix: modernize the docs regarding custom filters

- core/design.md
This should help people seeing POPO further down the docs to work out what it means, to reduce their cognitive load.
> Added POPO acronym where first explained

- core/form-data.md
GetResponseEvent is deprecated since Symfony 4.3, use RequestEvent instead
> Fix: GetResponseEvent deprecation

- core/errors.md
- GetResponseForControllerResultEvent is deprecated since Symfony 4.3, use ViewEvent instead
> Fix : GetResponseForControllerResultEvent depreciation

- core/data-providers.md
Synchronized with the `BlogPostItemDataProvider` example to show that the context is also available in the `getCollection()` function.
> data provider: added missing context

- core/data-providers.md
- core/extensions.md
This update is related to the following PR on APIP demo application: https://github.com/api-platform/demo/pull/162
The idea is to add cross-links between docs and the demo so it's easier for people to navigate and find useful stuff.
> demo: links to the related demo code

- admin/components.md
- outline.yaml
Add a Components section to admin docs, in order to describe each component of Api-Platform Admin, which React-Admin's Components it's based on and give examples and list of props for each.
Also added some missing propTypes: https://github.com/api-platform/admin/pull/333
> Add Components list 

- core/security.md
Includes `request` to available variables in security.
> Includes `request` to available variables in security

- core/jwt.md
Update with the new OpenApi documentation way. It works with Api Platform 2.6.0 beta 1
> Update JWT Documentation with the OpenApi way

- client-generator/nextjs.md
url with `https` gives a security error page : `ERR_SSL_PROTOCOL_ERROR`
> fixed typo in localhost url for next generator

- core/operations.md
> Update operations.md - PHP 8.0

- core/getting-started.md
> Update getting-started.md - Examples with PHP 8.0

- core/elasticsearch.md
Don't know if this is evident, but it had me boggling for a time. Index name should be lower snake case, not just lower case.
> Index name should be lower snake case

- core/data-providers.md
The usage of `ApiPlatform\Core\Exception\ResourceClassNotSupportedException` 
along the implementation of the `ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface` in the Data Provider seems redundant.
> Data Provider Exception vs Restricted interface

- core/swagger.md
Docs are currently showing examples using both Swagger V2 and V3 (swagger_context vs openapi_context). Changing examples to V3 by default (which is the version set by default) would make the documentation more consistant and avoid version mistakes for new users.
> Update Swagger documentation to use V3

- core/configuration.md
- core/openapi.md
Added documentation for the configurable asset package feature.
Matching feature PR in the core: https://github.com/api-platform/core/pull/3764
> Add documentation of configurable asset package

- core/identifiers.md
Sadly it took me a bit to find it, since I had misread the XSD. Could be useful to show the alternative configuration syntax for others like me.
> show XML syntax for @ApiProperty(identifier=true)

- core/mongodb.md
"integer" type was deprecated in doctrine/mongodb-odm 2.1 and will be removed in 3.0. Use "int" instead.
> Use "int" type instead of "integer" deprecated type

- core/elasticsearch.md
In the docs its really explicit that ElasticSearch should be populated with snake_case properties, but that gave me issues with normalizing nested objects. When I populated ElasticSearch with camelCase properties, serialization was Ok.
> Properties should be camel case

- extra/releases.md
Hi :wave: 
With the official release of [2.6.0](https://github.com/api-platform/core/releases/tag/v2.6.0) :tada:, here is my traditionnal PR to update **Release Process** with new stable version
Note that for the moment, the 2.6 branch doesn't exist yet in https://github.com/api-platform/core, so maybe we should wait this branch exist to merge this PR.
> [Releases] Update stable and old-stable branch

- client-generator/nextjs.md
Formik installation is required to display forms in Next generator.
> added formik to required dependencies

- core/subresources.md
> Update annotations of Subresources

- core/serialization.md
> Update annotations of Serialization

- core/pagination.md
Since api-platform/core 2.6: The use of the collection.pagination.client_items_per_page has been deprecated in 2.6 and will be removed in 3.0. Use defaults.pagination_client_items_per_page instead.
> Update client_items_per_page doc

- distribution/index.md
External link updated because it redirected to a .md working source.
As said in the README of [OWASP's Cheat Sheets repository](https://github.com/OWASP/CheatSheetSeries), markdown documents are not meant to be referenced :
> 🚩 Markdown files are the working sources and are not intended to be referenced in any external documentation, books or websites.
> Update index.md in distribution docs

- core/data-providers.md
- core/pagination.md
Adds details of new TraversablePaginator provided by https://github.com/api-platform/core/pull/3783.
It also includes some minor improvements to the documentation for pagination in customer Data Providers
> Add pagination info for custom data providers

- core/configuration.md
related to https://github.com/api-platform/core/issues/3730
> Swagger ui config patch

- core/data-persisters.md
> Complete example for Messenger with persistence

- core/validation.md
> Use Php8 attributes in validation.md

- core/filters.md
Complements https://github.com/api-platform/core/pull/4103
> Add `nulls_always_first` and `nulls_always_last` configuration options

- core/filters.md
Spotted a small typo inside the ApiFilter Annotation section.
> Fixes annotation typo in "Filters: ApiFilter Annotation" section

- core/graphql.md
> Add a note for user installing api platform with symfony flex

- core/controllers.md
There was a missing ] in the documentation causing `Uncaught Error: syntax error, unexpected token "class", expecting "]"` , this pull request fixes that
> Fix sintax error missing ]

- core/jwt.md
I add `tag` to JWT Token Operation in `JwtDecorator`, because before adding a tag to operation it looks likes:
After adding a tag to the operation it looks  likes this:
> Add tag to JWT Token Operation

- core/configuration.md
- core/events.md
https://github.com/api-platform/core/pull/4165
> Docs for QueryParameterValidation enabling/disabling

- distribution/debugging.md
I have updated the setting names to match Xdebug v3 setting names for Mac environments.
> Updated Mac env setting names for Xdebug v3

- deployment/minikube.md
- outline.yaml
> add a deploy on Minikube entry

- core/openapi.md
- core/operations.md
> Update docs with OpenApiFactoryInterface.

- core/graphql.md
Documents https://github.com/api-platform/core/pull/4143
> Document securing GraphQL fields (including associations) with `ApiProperty`

- core/subresources.md
corrected code sample that still used DocBlock notations in PHP8 Attributes
> correction in PHP code

- core/security.md
Documents https://github.com/api-platform/core/pull/4184
> Add notes on usage of `ApiProperty` `security_post_denormalize`.

- core/content-negotiation.md
- core/serialization.md
- Docs state that only JSON-LD is enabled by default, which isn't the case: https://github.com/api-platform/core/blob/de5988dacc871a7c1565aa8dea8c30102984cff9/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L216...L218
- While JSON may only enabled for the sake of Swagger, it still means that someone can use content negotiation anywhere on the API to request data in an unexpected format... perhaps bypassing a custom normalizer.  Important for security considerations developers are aware that more formats exist.
- (HTML is enabled by default too, but from what I see this doesn't provide a way to actually interact with the main API - so probably doesn't need to be mentioned?)
- Added the missing `myformat` example which is talked about but not shown.
- In the Serialization …
> Fixes to Content Negotiation / Serialization docs

- core/file-upload.md
> feat: Add documentation to test file uploads

- core/security.md
Add missing security yaml documentation
> docs: add missing security yaml documentation

- core/configuration.md
- core/url-generation-strategy.md
- outline.yaml
Related PR: https://github.com/api-platform/core/pull/3198
> feat: add URL generation strategy documentation

- distribution/index.md
Fix for issues such as https://github.com/api-platform/api-platform/pull/1937
> docs: always use the latest version of the images

- core/jwt.md
According to API Platform distribution.
> fix: change the service name

- distribution/testing.md
The core [```nelmio/alice```](https://github.com/nelmio/alice) changed the Faker dependency from [```fzaninotto/faker```](https://github.com/fzaninotto/faker) to [```fakerphp/faker```](https://github.com/fakerphp/faker).
https://github.com/nelmio/alice/pull/1059
> docs: change fakerPHP repository link

- core/serialization.md
Add missing serialization yaml documentation
> docs: add missing serialization yaml documentation

- core/default-order.md
Add missing yaml documentation in the default order section
> docs: add missing yaml documentation in the default order section

- core/default-order.md
- core/deprecations.md
- core/identifiers.md
- core/security.md
- core/serialization.md
Add yaml notation  for single property deprecation
> docs: add YAML notation for single property deprecation

- distribution/testing.md
See https://github.com/api-platform/api-platform/issues/1668
This notice can be removed again once that issue is resolved.
> docs: Add notice about disableReboot in tests with multiple requests

- core/errors.md
See https://github.com/api-platform/core/issues/4275
It was not clear that the HTTP status code chosen had an impact on whether the exception message will be sent to end users or not.
This PR adds a little explanation.
> docs(errors): document the different behaviour depending on status code

- core/controllers.md
- core/operations.md
Related: https://github.com/api-platform/core/pull/3263
> feat: thanks to the argument resolver, no need to use $data anymore

- core/controllers.md
When creating custom controllers the invoke method parameter name differs depending on the HTTP method.
> fix: Clarify __invoke distinction

- core/operations.md
The code sample for yaml and XML referenced a different controller then the code sample for PHP Attributes.
> docs: fix code sample to disable GET item operation

- deployment/docker-compose.md
Hi,
Here is an updated version of the documentation for ApiPlatform 2.6, current one is reflecting ApiPlatform 2.5. I struggled a bit to deploy in production, and finally came across that so I think that would be good for future users.
I think there are environment variables missing, I needed only those ones and didn't have time to make further testing. So be free to add those you know !
> Updating docker-compose for production

- core/security.md
The definition of the `security` attribute for an object property is currently wrong (only in YAML documentation).
The working configuration is the following:
```yaml
App\Entity\Book:
properties:
adminOnlyProperty:
attributes:
security: 'is_granted("ROLE_ADMIN")'
```
> docs(security): fix security definition for properties

- client-generator/react-native.md
Hello! 
The Expo CLI installation link change, a redirection was created but using the next link should be better and avoid a 404 link on API Platform documentation.
> docs: Update Expo CLI link

- core/serialization.md
In #1370, YAML documentation was added to the serializer page. In one instance, there were two PHP snippets being merged into a single code selector. Since the code selector cannot handle two PHP tabs (if you click the second one, the first one will be activated), this hid some information from that page.
This confused us a lot when setting up our embedding infrastructure, so I also added a sentence to describe the mechanism.
> Fix hidden PHP code snippet and add clarifying sentence

- client-generator/vuetify.md
In the section about i18n, instead of creating the file src/plugins/vuetify.js you need to create a file src/i18n.js
> Vuetify Generator: Fix section i18n

- core/operations.md
This PR clarifies PUT operation (or the fact that it acts more like a patch). Related issue: https://github.com/api-platform/core/issues/4344. Is it possible to see the future roadmap? It needs to be linked in the documentation.
> fix: Clarify PUT operation

- deployment/kubernetes.md
It took me some time to figure out how to add pods to consume a queue in kubernetes. This could be helpful for others.
> docs(kubernetes): add example for messenger deployment

- core/data-providers.md
On this page https://api-platform.com/docs/core/data-providers/
> fix: Broken links on Data Providers page

- core/serialization.md
`use Symfony\Component\Serializer\Normalizer\NormalizerInterface;` is not used anymore in `BookAttributeNormalizer`
https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis
> Update serialization.md : Remove unused import in BookAttributeNormalizer

- distribution/index.md
A suggestion for a way to mention doctrine mapping by annotations and attributes alongside.
Not sure about linking to "latest" (a moving target) but it seems to be common practice.
Resolves #1411
> docs: Doctrine ORM & attributes: mention their use

- core/events.md
The `Core` namespace is missing in link to github source file
> fix: broken link to EventPriorities src

- distribution/index.md
I'm not getting the SQL exception in 'Validating Data' section; empty strings are being stored instead of null being attempted.
The simplest fix is to remove the default empty strings from the entities.
This is using the Symfony and Composer install.
> docs: Remove empty string defaults from entities

- core/mercure.md
Since API Platform 2.6.5 the `mercure.hub_url` configuration is ignored if the Mercure bundle used is version ^0.3 and includes the `Discovery` class
The environment variables for the Mercure component are different so I have updated this documentation. I have not mentioned there is an option to use the `hub_url` configuration option. It may be worth mentioning in a comment on the configuration that the option is deprecated.
also see: https://github.com/api-platform/core/issues/4451
The link to the Symfony external parameter configuration was also broken.
> docs: Update the environment variables used for Mercure

- core/dto.md
Closes https://github.com/api-platform/docs/issues/1163.
> feat: add a documentation about the DataTransformerInitializer

- core/jwt.md
update doc for Symfony 5.3 compatibility, due to use deprecated code app does not work and return warnings
- New in version 5.3: The password_hashers option was introduced in Symfony 5.3. In previous versions it was called encoders.
- Deprecated since version 5.3: Guard authenticators are deprecated since Symfony 5.3 in favor of the new authenticator-based system.
Reference: 
https://symfony.com/doc/current/security.html#c-hashing-passwords
https://symfony.com/doc/current/security.html#guard-authenticators
> Update jwt.md for Symfony 5.3 compatibility

- deployment/minikube.md
caddy is a part of the dockerfile who is located in api folder. The current source folder does not exist
> source folder for build caddy change

- core/security.md
Fixes https://github.com/api-platform/api-platform/issues/1962#issuecomment-972459435.
> fix(security): request variable is only available at the resource level

- distribution/index.md
This is supported in 2.9: https://www.doctrine-project.org/2021/05/24/orm2.9.html
> fix: remove legacy doctrine php 8 attribute note

- core/filters.md
Miss enabled: true in doctrine filters yaml section
> Miss enabled: true in doctrine filters

- core/events.md
I corrected for this page, the component  it for sending email because SwiftMailer is no longer maintained. So I replaced by the component Mailer of Symfony.
> fix: [doc] Use the Mailer component instead of SwiftMailer

- core/events.md
Hello there, just fixing path to `EventPriorities` that seems to have moved.
> fix(doc): path to EventPriorities.php

- core/file-upload.md
I lost few hours on trying to figure why I had an empty filebag, using first or second file upload examples.
So I added a note.
> docs: add note on using PUT method to upload files

- distribution/debugging.md
> Bumped up xdebug version to support php 8.1

- core/pagination.md
Previous URL leads to 404
* Previous (404): https://github.com/api-platform/core/blob/main/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
* New (200): https://github.com/api-platform/core/blob/main/src/Core/Bridge/Doctrine/Orm/Extension/PaginationExtension.php
> fix: [doc] Update URL to point to the existing page

- core/data-persisters.md
Using classic decoration for the custom Data Persister in services.yaml will replace the core persister.
Probably this isn't the most common case scenario; normally you would _add_ your custom Data Persister to the chain of persisters instead of replacing it.
Use attribute binding instead, as already explained in SymfonyCasts' video.
> fix: [DOC] Use argument binding instead of decoration for Data Persister

- core/jwt.md
Hi,
this PR adds an information for the page about `JWT` authentication about how to make the tests fast.
The issue boils down to the very slow password hashers that are used in tests by default.
Each time we start a new project, or make a review of the existing one, we have to do it, because tests are extremely slow.
This is only one of the many optimizations available for the end developer, but let's start here. Other ones are listed in my blog post: https://maks-rafalko.github.io/blog/2021-11-21/symfony-tests-performance/#using-more-simple-password-hasher
In our cases, such change can improve tests speed by 2-5 times, depending on the project.
> docs: Add information about how to significantly improve the test suite

- .github/linters/.textlintrc
- distribution/index.md
I had to change these lines to fix some issues :
Line 406
```diff
-#[ORM\Column(type="text")]
+#[ORM\Column(type: "text")]
```
Line 420 and Line 481
```diff
-#[ORM\Column]
+#[ORM\Column(type: "datetime")]
```
> fix: diff of Doctrine annotations

- core/configuration.md
- core/performance.md
> feat(http_cache): document xkey purger

- core/jwt.md
Fix an error thrown while launching the AuthenticationTest because of the use of `self::$container`. Assign it in a variable first fixes the issue.
> Fix JWT authentication test file with static container

- core/filters.md
While trying to update to 2.7 I noticed that the example code in the custom filter section is wrong, so here's a small fix for that :)
> Fix custom filter example

- schema-generator/configuration.md
Add doc to option resolveTargetEntityConfigType option which allows to change the file type to YAML (or other formats eventually).
> Add multiple format support for resolve entity

- core/data-providers.md
I added example to help user to custom the Subresources
https://github.com/api-platform/core/issues/2321#issuecomment-437357871
It would be nice to set a trace in the official doc.
> add: [DOC] Custom Subresources Data Provider examples

- core/jwt.md
This PR adds a empty security array to authentication_token route. With this parameter set this route won't require authentication in openapi anymore.
> Add empty security option to remove security of authentication endpoint

- core/state-processors.md
The example for the `UserProcessor` was incorrect and still used the 2.6 format to call the decorated->process
> fix(doc): Update state-processors.md

- core/state-processors.md
Related to https://github.com/api-platform/core/pull/4859.
Supersedes https://github.com/api-platform/docs/pull/1583.
> fix: use the alias for the decorated state processor

- core/file-upload.md
The whole documentation for the version 2.7 is using the PHP attributes, so I feel, as Vich\UploadableBundle now supports them, we can use them for this bundle
> Use php 8 attributes for Vich\UploadableBundle

- core/jwt.md
Add missing `\` to new ArrayObject()
> fix(jwt): fix error on jwt decorator

- core/filters.md
Added an example in the Custom Filter section of the documentation to show how to use multiple properties in a custom filter
> Added example in custom filter

- core/filters.md
Hi,
This is a proposal to clarify a point with the service declaration and the _defaults section, which may not make perfect sense for newcomers.
> Doctrine ORM Filters - service declaration

- core/state-processors.md
- core/state-providers.md
Missing import addition in example code in Provider and Processor
For exemple :
additional with https://github.com/api-platform/docs/pull/1610
> Fix doc: add Operation in processor and provider

- core/openapi.md
The controller for registering the Swagger UI controller was the deprecated one.
> Fix registering the Swagger UI controller

- core/extensions.md
In the example, the methods `applyToCollection` and `applyToItem` implements incorrectly their definitions :
* [QueryCollectionExtensionInterface](https://github.com/api-platform/core/blob/3.0/src/Doctrine/Orm/Extension/QueryCollectionExtensionInterface.php)
* [QueryItemExtensionInterface](https://github.com/api-platform/core/blob/3.0/src/Doctrine/Orm/Extension/QueryItemExtensionInterface.php)
The problem may also exists on v2.7 documentation
> Fix CurrentUserExtension example

- extra/releases.md
On 15 Sept., 2022, a new release process has been announced starting from API Platform 3.0.
This PR provides some adjustments to the documentation to reflect those changes.
~~Remains to do: maybe a graph similar to the one we can see on [Symfony release page](https://symfony.com/releases#symfony-releases-calendar) to give a clear view of the process?~~
> Document the new release process announced at API Platform Conference

- distribution/index.md
https://github.com/felixfbecker/vscode-php-intellisense looks dead and the zobo fork seems to be the most popular fork
> Fix link to vscode intellisense

- core/subresources.md
Added some XML examples for subresource configuration, so users not configuring resource mapping with attributes can get an easier understanding of this.
> XML examples for subresources configuration

- core/testing.md
Remove $clientWithCredentials unused variable from AbstractTest class and adding type for $token variable.
> docs(testing): removing unused variable

- core/state-processors.md
I was having problems with what was described there because it basically broke entity deletion, see https://github.com/api-platform/core/discussions/5107 for details.
Does this make sense? Not entirely sure if it counts as fix or feature, just let me know, I'll update branches accordingly if necessary.
It's a mix of concerns, but I also adapted the example to use property promotion because 3.0 is requiring PHP 8.1 anyways, right?
> feat: Complete Doctrine ORM state processor example

- core/controllers.md
The documentation related to the version 2.7, 3.0 and 3.1 describing the custom operation configuration example contains a version 2.6 mandatory attribute ("path" instead of "uriTemplate").
> fix(controllers): replace "path" by "uriTemplate" attribute

- core/validation.md
The documentation says the following annotation should be used if you want to dynamically set validation groups using a service:
```php
#[ApiResource(validationContext: ['groups' => [AdminGroupsGenerator::class]])
```
However, this does not work. The API Platform validator only tries to fetch a service when a string is passed as `groups`:
```
if (
$this->container &&
\is_string($validationGroups) &&
$this->container->has($validationGroups) &&
($service = $this->container->get($validationGroups)) &&
\is_callable($service)
) {
```
> Fix documentation for using a service to generate validation groups

- core/controllers.md
The documentation leads to create a custom controller/action in order to create a custom operation.
However, API Platform provides an undocumented alternative: using the `ApiPlatform\Action\PlaceholderAction` which prevents to create a custom controller in order to create a custom operation.
Indeed, in complex cases, it prevents ending with a codebase overwhelmed by custom controllers which only exist because of the existence of the mandatory `controller` attribute.
In the long term, it could be a good idea for the Developer Experience to make this attribute optional so that API Platform uses the `ApiPlatform\Action\PlaceholderAction` by default.
> feat(controllers): using the PlaceholderAction

- core/errors.md
For some reason quotes were applied around `ProductNotFoundException::class` and `ProductWasRemovedException::class` in the docs.
> Typo: Removed quotes around XxxException:class constants

- core/mongodb.md
The [documentation](https://hub.docker.com/_/mongo) of the MongoDB docker image points out that the DB is stored at `/data/db`, described in the **Caveats** section under **Where to Store Data**.
> The -v /my/own/datadir:/data/db part of the command mounts the `/my/own/datadir` directory from the underlying host system as `/data/db` inside the container, where MongoDB by default will write its data files.
> Update container directory for volume mount

- core/subresources.md
- distribution/testing.md
In this context, "information" should not be pluralised.
Some nouns do not have a plural form. "Information" is one of them. Information is a [mass noun](https://en.wikipedia.org/wiki/Mass_noun). It has no plural form.
Additionally, CI flagged that "CLI" should be replaced with "command-line". This is resolved too.
> Replace "informations" with "information"

- core/user.md
```
class User
(...)
#[Assert\NotBlank(groups: ['user:create'])]
#[Groups(['user:create', 'user:update'])]
private ?string $plainPassword = null;
```
Per group  validator needs proper validationContext set to make it work.
> plainPassoword validator needs validationContext

- core/user.md
I realized after time that default validation group must be given explicitly when validationContext is used, so this add-on (#1712) PR for completeness.
> include default validation group

- core/file-upload.md
I didn't see the note and spent a lot of time figuring out what happens, because I was trying to Upload to an Existing Resource, and the note is not in this chapter. So I think it deserves to belong in the introduction paragraph.
> Note about PUT/PATCH in introduction §

- core/jwt.md
- core/state-processors.md
This is definitely missing in a documentation on how to use state processor with mongodb
> docs: add doctrine odm state processor

- distribution/index.md
I  didn't went through the whole page, but I spotted some tiny typos here and there :)
Thanks for your work :pray:
> Docs: Fix small typos in Getting started documentation page

- deployment/docker-compose.md
Hello,
Tried for a good amount of time to run the docker compose command proposed within the tutorial off a droplet but to no avail.  Upgrading to 2Go of RAM instead of the cheapest 1Go, did the trick.
Thought it was worth mentioning in the doc.
> Specify a minimym of 2Go RAM server

- core/elasticsearch.md
Mapping and one index for different models is deprecated, so removed it from the documentation. Also updated the ApiResource attribute.
Related to https://github.com/api-platform/core/pull/5450
> Update elasticsearch documentation

- core/openapi.md
When changing the name of a definition the newer `openapi_definition_name` key should be used, as `swagger_definition_name` does not seem to work when using api-platform/core 3.*
> Fixed swagger_definition_name to openapi_definition_name

- core/controllers.md
Since version [**2.7.0-alpha.1**](https://github.com/api-platform/core/blob/main/CHANGELOG.md#270-alpha1) (PR #3263), the __invoke() method parameter does not have to be named `$data` anymore. Code sample has been updated (`Book $data` => `Book $book`), but the warning has been forgotten and could be confusing.
> docs: remove obsolete warning in controllers.md

- core/identifiers.md
The example code for supportsTransformation expected `$types` (or `$type`) to be a scalaric value and not an array. This PR updates it to work with arrays.
See https://3v4l.org/Tn37N for "working" example code
> Fix: Update identifiers.md

- distribution/testing.md
Replace https://docs.hoppscotch.io/features (404 Not found) with https://docs.hoppscotch.io/documentation/features/rest-api-testing/
> Fix Hoppscotch broken URL

- admin/customizing.md
The previous link https://marmelab.com/react-admin/ don't lead to the doc but the link https://marmelab.com/react-admin/documentation.html works
> update link to marmelab's documention

- distribution/testing.md
> Add documentation to use Zenstruck Foundry instead of Alice

- core/bootstrap.md
Hi 👋 
I saw the closed PR #1574 and needed to look into API-Platform v3. As I did a test with the bootstrap documentation and needed to update the example code block to make it work for this purpose, is it possible to submit an update?
> Update bootstrap to v3

- core/security.md
**Original**: It means *than* for `PUT` or `PATCH` requests, ...
**Fixed**: It means *that* for `PUT` or `PATCH` requests, ...
> Fix typo in security.md

- distribution/testing.md
I was reading through docs looking for the usage of Alice to see it replaced by Foundry. That's fine. But the format of some preformatted blocks was not ;)
> Fix markdown to correctly close preformatted blocks

- core/performance.md
The suggested configuration in this documentation section triggers the following error:
> Unrecognized option "partial" under "api_platform.collection.pagination". Available options are "enabled", "enabled_parameter_name", "items_per_page_parameter_name", "page_parameter_name", "partial_parameter_name".
The correct parameter is already on the [pagination](https://api-platform.com/docs/core/pagination/#partial-pagination) docs
> Partial Pagination parameter updated in 3

- create-client/custom.md
This typo is also present in the documentation of the version [3.0](https://github.com/api-platform/docs/blob/3.0/create-client/custom.md).
> docs(create-client/custom): fix typo "cenario" by "scenario"

- extra/contribution-guides.md
This typo is also present in the documentation from version [2.5](https://github.com/api-platform/docs/blob/2.5/extra/contribution-guides.md) to version [3.0](https://github.com/api-platform/docs/blob/3.0/extra/contribution-guides.md).
> docs(contribution-guides): fix typo by adding a closing parenthesis

- core/filters.md
Core documentation on filters uses the void return type for filterProperty function in 1 place, but it's missing in the other example. This pull request adds the missing void return type.
> Add missing function return type in filters.md

- core/configuration.md
- core/graphql.md
Documentation of the proposed feature: api-platform/core#5711
> feat(graphql): allow to enable/disable the introspection query

- distribution/index.md
Replaced all the dead links reported by [Lychee](https://github.com/lycheeverse/lychee) with the new existing links.
> fix(distribution): replace dead links

- core/subresources.md
Just added yaml examples of usage of subresources.
> docs(subresources): add yaml examples

- distribution/index.md
Replace https://facebook.github.io/relay by https://relay.dev
> doc: replace the old relay url with the new one

- core/controllers.md
`groups` expect for array, but not a string
> [BUG] Fixed normalization context group value

- core/filters.md
- core/pagination.md
- core/performance.md
Currently indented text is being displayed as code blocks. 
I guess having no indentation is better than faulty code blocks for now.
> docs: remove indentation to fix faulty code blocks

- admin/authentication-support.md
The previously documented solution would only trigger introspection on the `/` route. Users directly navigating to a resource without being authenticated (eg. navigating to `/#/books` and then being redirected to the authentication page) would not hit the `<Route path="/">`, and thus wouldn't trigger introspection after authenticating.
If `redirectToLogin` is `true`, the `<Resource>`es shouldn't be defined in the application because otherwise they will register the specific routes, e.g. `/#/books`, meaning the `<Route path="/:any">` wouldn't be selected, and introspection also would not be triggered.
> Document how to get introspection to work on any route

- core/jwt.md
Unrecognized option document under security.providers.users Available options are chain, entity, id, ldap, lexik_jwt, memory, mongodb. 
Since symfony/security-bundle 6.2: The "enable_authenticator_manager" option at "security" is deprecated.
> chore: update jwt configuration

- core/performance.md
This is a long due fix that had been discussed here: https://github.com/api-platform/core/issues/5062
Since v2.2.7 the EagerLoadingExtension is only trigger for relation properties using Serializer groups but it is never stated in the documentation.
> fix(performance): add warning about Serializer groups being mandatory in order to trigger EagerLoadingExtension

- admin/openapi.md
- admin/real-time-mercure.md
- core/openapi.md
- create-client/nuxt.md
- create-client/quasar.md
- create-client/vuejs.md
- create-client/vuetify.md
Starting with 3.2, and since https://github.com/api-platform/core/pull/5808 and https://github.com/api-platform/api-platform/pull/2521, we cannot use /docs.json anymore
> Update mentions of OpenAPI docs.json to docs.jsonopenapi

- core/operation-path-naming.md
This functionality has moved (possibly in 3.1, so that might be the right target?), and I ended up with a deprecation warning following the docs.
> Update docs for new location of PathSegmentNameGenerator

- core/graphql.md
Fix var name
Trying to implement a TypeConverter, discover that the var used in docs is not the proper one. (See https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php#L40)
> Fix wrong variable name in documentation about TypeConverter

- distribution/debugging.md
Docs show `/srv/api` for `launch.json`, however the docker container now contains the app in `/app`.
> correct launch.json path mapping to /app

- core/content-negotiation.md
Variable name should be `$type` instead of `$class`, as shown in interface source: https://github.com/symfony/serializer/blob/6.4/Normalizer/DenormalizerInterface.php#L49
> Fix variable name

- extra/releases.md
Based on the example in the latest versions of Api Platform _(and the example just above)_, the _"stable"_ version should be `3.2`.
> docs(extra/releases): update Maintenance stable branch number

- core/file-upload.md
> remove a deprecation in upload docs

- deployment/kubernetes.md
- deployment/minikube.md
Adds missing `console` definition on code blocks, on light mode it doesnt show the text color correct in code blocks.
It was missing on minikube docs page and in one place on the kubernetes pages as reported here https://github.com/api-platform/api-platform/discussions/2617
> Add missing console styling to Minicube and Kubernetes code block docs in light mode

- core/messenger.md
Hi,
This PR fix some inline code : deprecation warning with MessageHandlerInterface.
```
Since symfony/messenger 6.2: Implementing "Symfony\Component\Messenger\Handler\MessageHandlerInterface" is deprecated, use the "Symfony\Component\Messenger\Attribute\AsMessageHandler" attribute instead.
```
> update messenger.md fix deprecation warning

- core/validation.md
The code example for the processor is missing the import for the Operation class.
>  fix: add missing import in code example in validation.md

- core/upgrade-guide.md
to _keep_ the doctrine inflector, set the value to true. By default, use symfony/string instead.
> fix wrong value

- core/subresources.md
missing line break was causing formatting error on https://api-platform.com/docs/core/subresources/
> typo on subresources.md

- distribution/testing.md
It's not an alternative to Alice anymore since it's in the snippets.
> Remove Foundry from alternatives

- create-client/nextjs.md
- deployment/docker-compose.md
- deployment/kubernetes.md
This pull request adds detailed instructions for building a Next.js client with Static Site Generation (SSG) locally with http in a Docker Compose environment.
The steps include adjustments to the compose.yaml and compose.prod.yaml files, building and starting the php service container, optional creation of a .env file for the Next.js client, building the pwa service, and finally bringing up the full project.
This setup ensures the Next.js client can access the API locally at build time for static page generation.
The last commit adapt the docker compose documentation to reflect the changes of this [PR](https://github.com/api-platform/api-platform/pull/2666) adding the MERCURE_PUBLIC_URL and
TRUSTED_HOSTS environment variables.
> Add instructions for building Next.js client with SSG locally in Docker Compose

- core/state-providers.md
Fix a typo in State Provider (missing the `service:` for autowire attribute).
Before :
```php
#[Autowire('api_platform.doctrine.orm.state.item_provider')]
```
After :
```php
#[Autowire(service: 'api_platform.doctrine.orm.state.item_provider')]
```
> fix: autowire item provider

- core/serialization.md
`ContextAwareNormalizerInterface` is deprecated since Sf 6.1 and remove in Sf 7
> fix: Use NormalizerInterface

- core/jwt.md
Hello,
This PR removes the deprecated (removed in symfony 7.0) `security.enable_authenticator_manager`  option
> docs: remove enable_authenticator_manager option

- core/subresources.md
Docs PR for Link Security feature
> feat(subresource): Link security

- core/state-processors.md
Void can only be used as a standalone type
> docs: remove void in union type

- core/file-upload.md
V3.3 has become more strict about input format checking (intentionally or otherwise) and users need to be more rigorous in allowing multipart when using it for file uploads.
Prior to v3.3, I suspect people should have been defining this, but it wasn't being checked, so many won't have done.
Not sure my "note" format is in the preferred document style - possibly we don't want to mention the version for example?  Feel free to edit or request changes.
> Note requirement to explicitly enable multipart as an input format

- deployment/minikube.md
Linked to the PR for adding Skaffold configuration: https://github.com/api-platform/api-platform/pull/2457
If the PR on api-platform/api-platform is refused, and this PR for the documentation is accepted, need to change the doc before merging (replace links to /api-platform/helm/skaffold*.yaml by the content of this files.)
> add documentation for minikube deployment using skaffold.

- core/user.md
`User|void` generate this error `Compile Error: Void can only be used as a standalone type` with PHP 8.3 (at least). Removing void fix it.
> Update user.md update PasswordHasher code sample to fix syntax error

- core/extensions.md
> added a note about the default rootAlias to extensions.md

- core/openapi.md
There is a trailing `attributes` in the documentation. `openapiContext` should comes directly inside class attributes.
See how it is handled here: https://github.com/api-platform/core/blob/40fd6006bff137893cbe465ddb1d5bceca133ecc/src/JsonSchema/SchemaFactory.php#L153
> doc: Update openapi.md properties issue

- core/performance.md
Hello,
This pull request updates Souin setup in docs, see https://github.com/dunglas/frankenphp/issues/976#issuecomment-2296050761
> feat(performance): update Souin setup & enable Cache-Control public in docs

- core/operations.md
The docs points to an issue already closed. The disclaimer about PUT operation is not useful anymore.
> Remove obsolete disclaimer

- deployment/kubernetes.md
Kubernetes deployment doc wasn't up to date with new frankenphp image (instead of php+caddy images)
> Update kubernetes.md to be complient with frankenphp

- core/serialization.md
The image is broken all the way down to the [v2.1 docs](https://api-platform.com/docs/v2.1/core/serialization/), but not sure if it should be fixed all the way back to that branch (might make merging up to the latest version a bit difficult)
> Fix path to SerializerWorkflow.png image

- core/performance.md
Use latest Souin/cache-handler version
> Use latest Souin/cache-handler version in the documentation

- core/getting-started.md
- core/operations.md
- core/serialization.md
- distribution/index.md
> feat: PUT is now disabled by default

- core/configuration.md
`keep_legacy_inflector` was deprecated and 3.3 and supposed to removed by 4.0
> fix(doc): Remove keep_legacy_inflector from docs

- core/openapi.md
This is currently an undocumented feature as fas as I know. I think it would make sense to include it in the documentation, because for some it might be very useful.
> Document spec-version option usage

- distribution/debugging.md
'Debug' concept is widely understood as the way xdebug step-debugging runs, so there is an explicit need to use XDEBUG_SESSION in order to enable step-debugging. Otherwise it seems not to work, cause providing `XDEBUG_MODE=debug` is not enough if using the api-platform distribution on its release v3.3.7 (which is the latest currently)
> Added XDEBUG_SESSION=1 to console instruction enabling xdebug

- core/getting-started.md
Removed an unnecessary empty block in the "CAUTION" section of the documentation. This change cleans up the formatting and ensures the documentation is more readable and concise.
While fixing this I realized that the rendering is not very nice on the doc site @dunglas.
Expected rendering (with the actual code):
But in the documentation website we have this rendering:
> [Core > getting started] Remove empty block quote

- core/filters.md
I noticed that starting from api-platform:4.0 the `openapi` property expects `ApiPlatform\OpenApi\Model\Parameter` object instead of the array in the filter description.
> patch(filters) fix openapi property in custom filter documentation

- core/filters.md
Change the function name from "provider" to "provide"
> fix: Change typo in filters doc for GroupsParameterProvider function class

- core/getting-started.md
If you try to require with `API` in uppercase, it returns this error
Whereas lowercase `api` it goes fine
> Change composer require package name

- core/events.md
- core/extending.md
- core/graphql.md
The initial aim was to update the `core/graphql.md`, but  I soon realized, with @soyuka's help, that some parts didn't work like that anymore in API Platform 4 (for example the "stages").
So we decided to move and rewrite some parts in `core/extending.md`  and add a warning in `core/events.md` documentations.
> Update graphql, events & extending docs for Laravel and v4

- core/filters.md
We have to use =>
use ApiPlatform\Doctrine\Orm\Filter\ExistsFilter;
Instead of :
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\ExistsFilter;
> docs:Update filters.md - change wrong dependency injection

- core/state-processors.md
Related to #2018 
Waiting a response from @dunglas to create a command for laravel to generate state processors like this 
```console
php artisan make:state-processor
```
As we can already do with the Symfony variant with:
```console
bin/console make:state-processor
```
See related code:  https://github.com/api-platform/core/pull/6708
> Add Laravel support to state processors documentation

- core/state-providers.md
Related to #2019 
Waiting a response from @dunglas  to create a command for laravel to generate state providers like this 
```console
php artisan make:state-provider
```
As we can already do with the Symfony variant with:
```console
bin/console make:state-provider
```
See related code:  https://github.com/api-platform/core/pull/6708
> Add Laravel support to state providers documentation

- laravel/index.md
Relates to this PR: https://github.com/api-platform/core/pull/6751
> [Laravel] Add Caching documentation

- core/upgrade-guide.md
Update to upgrade guide - 
extra_properties should live under 'default:'
> Correction to upgrade guide

- CONTRIBUTING.md
Since we have a README.md file (#2050), the code of conduct is not in the first index page, so the link to the current code of conduct, using the header, is broken. It's more reliable to point to it using ` #coc-ov-file`.
> docs(contributing): fix broken link to code of conduct

- core/extending.md
As @soyuka pointed out, this PR adds ContentNegotiationProvider, which is missing from the System providers and processors diagram.
> fix: missing ContentNegotiationProvider

- core/events.md
- core/extensions.md
- core/filters.md
- core/mongodb.md
- core/performance.md
- core/serialization.md
- symfony/index.md
replace “latest” with “current” for doctrine project links
> fix: use stable version for doctrine projects

- core/filters.md
Do the same as #2057 for `OrderFilterInterface` constants.
> refactor(doctrine): reference order filters constants from interface

- extra/philosophy.md
- laravel/index.md
Fixes CI jobs like https://github.com/api-platform/docs/actions/runs/11899064908/job/33156882009
> fix(ci): incorrect term “must-have” for NATURAL_LANGUAGE

- core/configuration.md
Update the configuration reference documentation by adding the API Platform PHP configuration for Laravel. 
It is necessary, among other purposes, to document the following PR: https://github.com/api-platform/core/pull/6741
> docs: include Laravel for config reference

- core/subresources.md
Adds Laravel-specific documentation sections for subresources
> Subresources doc updated to include Laravel-specific parts

- CONTRIBUTING.md
- admin/getting-started.md
- core/file-upload.md
- core/graphql.md
- core/json-schema.md
- core/jwt.md
- core/messenger.md
- core/mongodb.md
- core/openapi.md
- core/testing.md
- create-client/nextjs.md
- deployment/docker-compose.md
- deployment/heroku.md
- deployment/kubernetes.md
- deployment/minikube.md
- deployment/traefik.md
- schema-generator/getting-started.md
- symfony/index.md
- symfony/testing.md
Partially solves #1995 by solving these 2 subtasks : 
- "Remove all `docker compose` prefixes for commands, as we don't use Docker for Laravel"
- "Explain how to run commands with Symfony and Docker in the `symfony/index.md`"
:warning:  Don't forget to check the checkbox in the issue if the PR is merged
> refactor: clean up docker cmds and improve code blocks

- core/file-upload.md
Alternative to https://github.com/api-platform/docs/pull/2064.
> fix(file-upload): always JSON encode field values

- core/filters.md
**Description:**
This PR fixes a typo in the documentation where the "Creating Custom Doctrine ORM filters" heading is duplicated. The second heading, which links to the Elasticsearch filters documentation (https://api-platform.com/docs/core/elasticsearch-filters/#creating-custom-elasticsearch-filters), is incorrectly labeled as "Creating Custom Doctrine ORM filters."
**Changes:**
Updated the second duplicate heading to "Creating Custom Elasticsearch filters" for clarity and accuracy.
**Why this change is needed:**
The duplicate heading may confuse users, as the content under the second heading pertains to Elasticsearch filters rather than Doctrine ORM filters. Correcting this ensures the documentation is clear and easy to navigate.
Checklist:
- Reviewed and verified changes locally
- …
> Fix duplicate "Creating Custom Doctrine ORM filters" heading in documentation

- core/state-providers.md
While trying the exact example, I found an [issue](https://3v4l.org/mStY0):
> New expressions are not supported in this context
> Replace const with property in state provider examples

- core/getting-started.md
- outline.yaml
- symfony/migrate-from-fosrestbundle.md
This documentation only concerns the Symfony ecosystem, so we should move it from `core/` to `symfony/`.
Also, it fixes several broken links.
> docs(fosrestbundle): move from core to symfony and update

- core/form-data.md
Add Laravel support and update the documentation by removing deprecated parts (such as DunglasAngularCsrfBundle and events).
> docs(form-data): support for laravel and update

- core/elasticsearch.md
Adds compatibility with Laravel and improves documentation redirections (more accurate).
> docs(elasticsearch): compatibility with laravel and improve

- core/extending-jsonld-context.md
Adds compatibility with Laravel
> docs(extending-jsonld-context): compatibility with laravel

- core/operation-path-naming.md
Adds compatibility with laravel
> docs(operation-path-naming): compatibility with laravel

- core/extensions.md
- core/graphql.md
- core/subresources.md
As seen with @dunglas, [Doctrine extensions documentation ](https://api-platform.com/docs/core/extensions/) should be in "API PLATFORM FOR SYMFONY" section.
**EDIT:
We'll leave the extensions in `core`, but explain better that it's for doctrine & elasticsearch only.**
:information_source: Also fix several links
> refactor(ext): move doctrine extensions from core to symfony

- core/dto.md
Do you think I should also mention these resources or integrate parts in the doc? 
- https://www.youtube.com/watch?v=IVJjADhU7WM
- https://speakerdeck.com/weaverryan/create-the-dto-system-of-your-dreams-stateoptions-plus-entityclass
> docs(dto): improve dto documentation and support laravel

- core/performance.md
For more info see https://github.com/api-platform/docs/pull/2070#issue-2698462074
> docs(perfs): compatibility with laravel and reorganize

- core/default-order.md
For more info see https://github.com/api-platform/docs/pull/2070#issue-2698462074
> docs(default-order): compatibility with laravel

- core/pagination.md
As seen with @dunglas, it's better to use `App\ApiResource` instead of `App\Entity` to suit Symfony and Laravel.
It avoids making the equivalence between models and entities in code examples (namespaces among others). 
By the way, I've adapted the comments to be compatible with the 2 as well, so
`// api/src/Entity/Book.php` becomes `// api/src/ApiResource/Book.php with Symfony or app/ApiResource/Book.php with Laravel`.
> docs(pagination): support for laravel and reorganize

- core/index.md
- outline.yaml
- symfony/user.md
This documentation only concerns Symfony, so we should move it from `core/` to `symfony/`.
> docs(entity): move from core to symfony

- core/extending.md
- outline.yaml
- symfony/controllers.md
- symfony/migrate-from-fosrestbundle.md
Documentation moved from `/core` to `/symfony`, updated and invalid links fixed
> docs(controllers): move from core to symfony and update

- core/content-negotiation.md
YAML is now a RFC and has an official media type: https://www.rfc-editor.org/rfc/rfc9512.html#name-media-type-application-yaml
> use newly registered YAML media type

- core/client-integration.md
- outline.yaml
> docs(client-integration): introduce documentation

- symfony/file-upload.md
Cleaned up the code by removing an unused import statement. This helps improve readability and maintainability of the documentation. No functional changes were introduced.
> [bug] Remove unused SaveMediaObject import from file-upload.md

- core/openapi.md
This issue was introduced at [#2080](https://github.com/api-platform/docs/pull/2080/files#diff-ddca92eb923034384e57fb330d4e43f5d8c3901ad390de86a8d0899128c9e390R640).
The controller service for this route is [`api_platform.action.documentation`](https://github.com/api-platform/core/blob/825833cfee432e6b0988882d019b4fe4a03f63d5/src/Symfony/Bundle/Resources/config/routing/docs.xml#L8-L12).
> fix: service controller references for "api_doc" route

- core/openapi.md
Added documentation for Laravel on overriding the default OpenAPI UI template.
> docs(openapi): add custom UI template override for Laravel

- core/serialization.md
Closes #2114 
- Added detailed documentation about the deprecation of annotations in favor of attributes for Symfony >= 7.0.
- Updated configuration examples for both annotation-based and attribute-based serializers.
- Fixed a broken link to doctrine documentation (ManyToOne relation).
> docs(serializer):  deprecation of annotations and fix broken link

- laravel/filters.md
Documentation PR for https://github.com/api-platform/core/pull/6806
> docs(laravel): boolean filter

- core/content-negotiation.md
fixes https://github.com/api-platform/docs/issues/994
> docs(content-negociation): document how to declare an encoder for custom format

- core/configuration.md
- core/graphql.md
Replaces #2107 to document https://github.com/api-platform/core/pull/6880 with Laravel support and some improvements.
PR started by @mauriau
> feat(graphql): enable configurable max_query_depth and max_query_complexity

- admin/authentication-support.md
- admin/openapi.md
The pull request enhances the documentation for the Admin section by adding a comprehensive example of a custom dataProvider.
**Goal:**
To provide a more advanced, real-world example for developers who need to extend the OpenApiAdmin component with custom authentication and error handling.
> docs(admin): openapi custom data provider example

- core/dto.md
- core/events.md
- core/identifiers.md
- core/serialization.md
I'm not sure if it was intentional or not to use untyped properties. Providing examples using the modern syntax is useful for the readers.
> Use property type

- core/openapi.md
Without the `_format` option, the resulting route is not able to expose other paths like `/api_documentation.jsonopenapi`.
> fix: multiple formats for custom "api_doc" route example

- core/openapi.md
The command displayed as grey on grey and was not readable
> [UI] Fix bad command line appearance

- symfony/file-upload.md
Having multipart at the first position of enabled formats in `api_platform.yaml` negatively affects the api (swagger) documentation. For some reason, all requests will be generated with 'accept: multipart/form-data', which is wrong for most endpoints. See the following GET request which is generated with the "accept: multipart/form-data" header (see the curl command below):
This leads to responses with the error message "Serialization for the format "multipart" is not supported.".
Switching the formats in `api_platform.yaml` to have `jsonld` at the first position solves this issue:
formats:
jsonld: ['application/ld+json']
multipart: ['multipart/form-data']
Now, the request is generated and done properly with the correct accept header:
I was also able to reproduce this in version 4.0. This …
> Docs (Symfony file upload): Change order of enabled formats

- core/deprecations.md
Fix which uses the correct namespace for the attribute groups from the Symfony serializer component.
> Fix typo in deprecations.md for Groups attribute

- core/elasticsearch.md
Support for Elasticsearch 8 was introduced in [3.2.0](https://github.com/api-platform/core/releases/tag/v3.2.0) but the docs were never updated to reflect this. They currently states on the [Elasticsearch page](https://api-platform.com/docs/core/elasticsearch/)
> Be careful, API Platform only supports Elasticsearch >= 7.11.0 < 8.0.
This PR updates that note to reflect the current [composer.json constraints](https://github.com/api-platform/core/blob/88f5ac50d20d6510686a7552310cc567fcca45bf/src/Elasticsearch/composer.json#L30).
Note that [Elasticsearch 9](https://www.elastic.co/guide/en/elastic-stack/9.0/release-notes-elasticsearch-9.0.0.html) is currently in RC. It's unclear from their documentation if there will be breaking changes in regards to Api-platforms integration.
> Update note on supported Elasticsearch versions to include 8.4+

- deployment/kubernetes.md
`main` branch is not in use anymore. This changes it to the latest, which currently is `4.1`.
> Update kubernetes info link to CD script

- core/form-data.md
- core/graphql.md
- core/serialization.md
> fix: SerializerContextBuilderInterface namespace

- outline.yaml
renaming of `admin/schema-org.md` to `admin/schema.md` in #2141 did lead to crash of deployment, as menu can not be generated anymore in build: https://github.com/api-platform/docs/actions/runs/14727992117/job/41335196797
> fix(deployment): fix menu generation after doc revamp of #2141

- core/openapi.md
The location of the blade files to override the default documentation template should be under `resources/views/vendor/api-platform`.
> Update Laravel Blade documentation view override location

- laravel/index.md
> laravel groups

- laravel/filters.md
Added a practical example for using DateFilter. As someone coming from a Laravel background, I found it difficult to extract the needed usage patterns from the existing Symfony documentation. More examples across the docs would help newcomers adopt the tools more quickly.
> improve DateFilter usage explanation with example

- symfony/user.md
This pull request fixes two small issues in the User authentication example:
- Removed unused imports: `ApiFilter` and `ApiProperty` in the `User` entity
- Added missing `use App\Entity\User;` in the `UserPasswordHasher` processor
These corrections ensure that the example code works as expected when copied directly, and help improve the overall clarity and accuracy of the documentation for developers following it step by step.
> Fix incorrect and unused imports in User entity documentation

- symfony/file-upload.md
Correct configuration steps order to allow to make a request `POST /media_objects`.
Resolves: https://github.com/api-platform/api-platform/issues/2713
> fix(File upload): correct steps order

- symfony/user.md
Solves https://github.com/api-platform/docs/issues/2165
In my opinion, there is no need for additional references to 'eraseCredentials' in the documentation, and it should not cause any issues. So I purposed to remove this Symfony deprecation as reported in  https://github.com/api-platform/docs/issues/2165.
> feat(user): remove deprecated eraseCredentials

- symfony/index.md
No space cause an error `404: Not Foundcurl: (6) Could not resolve host: sh`
> typo(docs): add space to sync command

- symfony/user.md
This PR updates the user authentication example to ensure compatibility with Symfony 7.3 and apply current security best practices:
- **Restores the `eraseCredentials()` method** in the `User` entity:
Although deprecated since Symfony 7.1, the method is still required by the `UserInterface` in Symfony 7.3.
It will be removed in Symfony 8.0, but must remain for now to avoid runtime errors.
- **Manually clears the `plainPassword` field** in the processor after hashing:
Since `eraseCredentials()` is no longer called automatically, it's now the developer’s responsibility to ensure sensitive data is cleared.
This avoids leaving passwords in memory or exposing them via logs, exceptions, or debug tools.
These changes make the example code functional and secure across current Symfony versions.
> Restore eraseCredentials() for Symfony 7.3 compatibility (until Symfony 8.0) and clear plainPassword manually

- core/graphql.md
In the newer version, I see that it is like /graphql not /api/graphql.
> [R] docs: clarify default GraphQL endpoint for Symfony and Laravel variants

- core/filters.md
Improves menu order for Parameter providers
> fix(filters): menus order

- symfony/index.md
As using docker install way is the "recommended" way, all commands specific to this tutorial should use the "docker way"
> Commands in tutorial should reflect the recommand install way

- core/graphql.md
graphql-normalizer needs to be injected
> graphql.md: add "MediaObject Normalization" chapter

- core/doctrine-filters.md
- core/elasticsearch-filters.md
- core/filters.md
- laravel/filters.md
Adds documentation for https://github.com/api-platform/core/pull/7121, https://github.com/api-platform/core/pull/7364 and https://github.com/api-platform/core/pull/7355.
Also fixes https://github.com/api-platform/docs/issues/2202
> docs: add new search filters syntax and the new make filter command

- symfony/index.md
Corrected the phrasing from "Checkout" to "Check out" for clarity. ("to check something out", in this case the code, _VS_ "checkout" as the place where someone pays for their purchases)
> doc: fix small typo

- core/serialization.md
A small change to clarify the docs are talking about PHP [properties](https://www.php.net/manual/en/language.oop5.properties.php) rather than [attributes](https://www.php.net/manual/en/language.attributes.overview.php).
> Change "attributes" to "properties" in The Serialization Process document
